### DISCUSSION TITLE
No success w/Home Assistant device tracker (location)

### DISCUSSION THREAD

**Discussion by krelltunez** [teslamate-org/teslamate#1120] [General]
Hi all.  I've got Teslamate working quite well for a couple months now (former TeslaFi user), and have integrated it with HA nicely.  I'm using Teslamate for real-time info, and Tasker (via my Android phone) for functionality (wake, turn on HVAC, etc.) - all via a nice Lovelace dashboard.

What's missing is the location tracker.  Usually, I just click over to Teslamate, but it would be nice to have some rudimentary location data reported into HA (for visibility outside my home network and also for use by automations).  

I have twice tried to follow the instructions [here](https://docs.teslamate.org/docs/integrations/home_assistant/) and I have not been successful.  Usually my automation fails and the location never updates.

Has anyone had success setting up location tracking?  I guess I'm confused why the Teslamate geo-fences can't be shared via MQTT with HA.  I even tried using an iframe panel, but since HA uses HTTPS (at least in my setup), I'm unable to frame an HTTP site.  Perhaps another question is whether there's any way to have Teslamate use HTTPS also (because then I think using an iframe panel would be possible).

Just curious as to what others have experienced.  Not a gripe on Teslamate (which has been great) or Home Assistant (which I love and adore).

Cheers!

**Comment by DarrenEwaniuk** [comment]
This works fine for me, but I moved the sensors into the configuration.yaml file itself as I had a ton of sensors already in configuration.yaml
This might be your issue, if you have any sensors defined in configuration.yaml, the #include will probably fail unless you move all sensors into sensors.yaml, or move all teslamate sensors into configuration.yaml

In configuration.yaml (same as documentation other than commenting out the sensor include file)

```
#teslamate
proximity:
  home_tesla:
    zone: home
    devices:
      - device_tracker.tesla_location
    tolerance: 10
    unit_of_measurement: km

tesla:
  username: !secret tesla_username
  password: !secret tesla_password
  scan_interval: 3600

#sensor: !include sensor.yaml
#/teslamate
```

Then later in configuration.yaml (with names made more human readable, new sensors added, and sensors not relevant to North America or Model 3 commented out)
```
#teslamate
  - platform: mqtt
    name: Tesla battery level
    state_topic: "teslamate/cars/1/battery_level"
    unit_of_measurement: "%"
    icon: mdi:battery-80

  - platform: mqtt
    name: Tesla charge energy added
    state_topic: "teslamate/cars/1/charge_energy_added"
    unit_of_measurement: "kWh"
    icon: mdi:battery-80

  - platform: mqtt
    name: Tesla charge limit
    state_topic: "teslamate/cars/1/charge_limit_soc"
    unit_of_measurement: "%"
    icon: mdi:battery-80

  - platform: mqtt
    name: Tesla charge port door open
    state_topic: "teslamate/cars/1/charge_port_door_open"
    icon: mdi:car-door

  - platform: mqtt
    name: Tesla charger actual current
    state_topic: "teslamate/cars/1/charger_actual_current"
    unit_of_measurement: "A"
    icon: mdi:battery-80

#  - platform: mqtt
#    name: Tesla charger phases
#    state_topic: "teslamate/cars/1/charger_phases"
#    icon: mdi:power-plug

  - platform: mqtt
    name: Tesla charger power
    state_topic: "teslamate/cars/1/charger_power"
    unit_of_measurement: "kW"
    icon: mdi:ev-station

  - platform: mqtt
    name: Tesla charger voltage
    state_topic: "teslamate/cars/1/charger_voltage"
    unit_of_measurement: "V"
    icon: mdi:gauge

  - platform: mqtt
    name: Tesla display name
    state_topic: "teslamate/cars/1/display_name"
    icon: mdi:car

  - platform: mqtt
    name: Tesla estimated range
    state_topic: "teslamate/cars/1/est_battery_range_km"
    unit_of_measurement: "km"
    icon: mdi:map-marker-path

  - platform: mqtt
    name: Tesla healthy
    state_topic: "teslamate/cars/1/healthy"
    icon: mdi:car-connected

  - platform: mqtt
    name: Tesla ideal range
    state_topic: "teslamate/cars/1/ideal_battery_range_km"
    unit_of_measurement: "km"
    icon: mdi:map-marker-path

  - platform: mqtt
    name: Tesla inside temperature
    state_topic: "teslamate/cars/1/inside_temp"
    unit_of_measurement: °C
    icon: mdi:thermometer

  - platform: mqtt
    name: Tesla latitude
    state_topic: "teslamate/cars/1/latitude"
    icon: mdi:crosshairs-gps

  - platform: mqtt
    name: Tesla locked
    state_topic: "teslamate/cars/1/locked"
    icon: mdi:lock

  - platform: mqtt
    name: Tesla longitude
    state_topic: "teslamate/cars/1/longitude"
    icon: mdi:crosshairs-gps

  - platform: mqtt
    name: Tesla odometer
    state_topic: "teslamate/cars/1/odometer"
    unit_of_measurement: km
    icon: mdi:gauge

  - platform: mqtt
    name: Tesla outside temperature
    state_topic: "teslamate/cars/1/outside_temp"
    unit_of_measurement: °C
    icon: mdi:thermometer

#  - platform: template
#    sensors:
#      tesla_park_brake:
#        friendly_name: Park Brake
#        value_template: >-
#          {% if is_state('sensor.tesla_shift_state', 'P') %}
#            true
#          {% else %}
#            false
#          {% endif %}

  - platform: mqtt
    name: Tesla plugged in
    state_topic: "teslamate/cars/1/plugged_in"
    icon: mdi:ev-plug-tesla

  - platform: mqtt
    name: Tesla rated range
    state_topic: "teslamate/cars/1/rated_battery_range_km"
    unit_of_measurement: "km"
    icon: mdi:map-marker-path

  - platform: mqtt
    name: Tesla scheduled charging start
    state_topic: "teslamate/cars/1/scheduled_charging_start_time"
    icon: mdi:clock-outline

  - platform: mqtt
    name: Tesla sentry mode
    state_topic: "teslamate/cars/1/sentry_mode"
    icon: mdi:cctv

#  - platform: mqtt
#    name: Tesla shift state
#    state_topic: "teslamate/cars/1/shift_state"
#    icon: mdi:car-shift-pattern

  - platform: mqtt
    name: Tesla speed
    state_topic: "teslamate/cars/1/speed"
    icon: mdi:speedometer

  - platform: mqtt
    name: Tesla state
    state_topic: "teslamate/cars/1/state"
    icon: mdi:car-connected

  - platform: mqtt
    name: Tesla time to full charge
    state_topic: "teslamate/cars/1/time_to_full_charge"
    unit_of_measurement: "hr"
    icon: mdi:clock-outline

  - platform: mqtt
    name: Tesla windows open
    state_topic: "teslamate/cars/1/windows_open"
    icon: mdi:car-door

  - platform: mqtt
    name: Tesla version
    state_topic: "teslamate/cars/1/version"
    icon: mdi:alphabetical

  - platform: mqtt
    name: Tesla update available
    state_topic: "teslamate/cars/1/update_available"
    icon: mdi:gift

#Added
  - platform: mqtt
    name: Tesla doors open
    state_topic: "teslamate/cars/1/doors_open"
    icon: mdi:car-door

  - platform: mqtt
    name: Tesla trunk open
    state_topic: "teslamate/cars/1/trunk_open"
    icon: mdi:car-door

  - platform: mqtt
    name: Tesla frunk open
    state_topic: "teslamate/cars/1/frunk_open"
    icon: mdi:car-door

  - platform: mqtt
    name: Tesla preconditioning
    state_topic: "teslamate/cars/1/is_preconditioning"
    icon: mdi:car-defrost-rear

  - platform: mqtt
    name: Tesla climate on
    state_topic: "teslamate/cars/1/is_climate_on"
    icon: mdi:fan

  - platform: mqtt
    name: Tesla user present
    state_topic: "teslamate/cars/1/is_user_present"
    icon: mdi:account
#/teslamate
```
In automations.yaml (reordered automatically after using GUI functions)
```
- id: '1598159827867'
  alias: Update Tesla location as MQTT location updates
  initial_state: true
  description: ''
  trigger:
  - platform: mqtt
    topic: teslamate/cars/1/latitude
  - platform: mqtt
    topic: teslamate/cars/1/longitude
  condition: []
  action:
  - data_template:
      dev_id: tesla_location
      gps:
      - '{{ states.sensor.tesla_latitude.state }}'
      - '{{ states.sensor.tesla_longitude.state }}'
    service: device_tracker.see
  mode: single
```  
The complete contents of  known_devices.yaml (same as in the docs)
```
tesla_location:
  hide_if_away: false
  icon: mdi:car
  mac:
  name: Tesla
  picture:
  track: true
```

And the following in configuration.yaml is totally optional.  I've added this to allow reporting on door status from Google Assistant, and to open/close doors/trunks and activate/deactivate other features (sentry mode, etc) without using the native Home Assistant Tesla integration.

Note; Open/Close functions themselves send a message to Tasker Autoremote with the Tesla Tasker plugin to actually open and close so that I don't need to use the HA Tesla native functionality, just remove the sections after close_cover: and open_cover: for state report functionality only.  Or use the HA Tesla functionality by commenting the open_cover and close_cover sections and un-commenting the following comment blocks, replacing "madoka" (my Tesla name) with your Tesla's name.
```
rest_command:
  autoremote_phone_command:
    url: "https://autoremotejoaomgcd.appspot.com/sendmessage?key=this_is_my_autoremote_key&message={{ action }}=:={{ message }}"
    method: GET
    content_type: 'application/json'

cover:
  - platform: template
    covers:
      tesla_frunk:
        device_class: door
        friendly_name: "Tesla Frunk"
        value_template: "{{ is_state('sensor.tesla_frunk_open', 'true') }}"
        icon_template: >-
          {% if is_state("sensor.tesla_frunk_open", "true") %}
            mdi:car-door
          {% else %}
            mdi:car-door-lock
          {% endif %}
        open_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode frunk"
            message: "open"
        close_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode frunk"
            message: "close"
#        open_cover:
#          service: lock.unlock
#          entity_id: lock.madoka_frunk_lock
#        close_cover:
#          service: lock.lock
#          entity_id: lock.madoka_frunk_lock
      tesla_trunk:
        device_class: door
        friendly_name: "Tesla Trunk"
        value_template: "{{ is_state('sensor.tesla_trunk_open', 'true') }}"
        icon_template: >-
          {% if is_state("sensor.tesla_trunk_open", "true") %}
            mdi:car-door
          {% else %}
            mdi:car-door-lock
          {% endif %}
        open_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode trunk"
            message: "open"
        close_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode trunk"
            message: "close"
#        open_cover:
#          service: lock.unlock
#          entity_id: lock.madoka_trunk_lock
#        close_cover:
#          service: lock.lock
#          entity_id: lock.madoka_trunk_lock
      tesla_doors:
        device_class: door
        friendly_name: "Tesla Doors"
        value_template: "{{ is_state('sensor.tesla_doors_open', 'true') }}"
        icon_template: >-
          {% if is_state("sensor.tesla_doors_open", "true") %}
            mdi:car-door
          {% else %}
            mdi:car-door-lock
          {% endif %}
        open_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode doors"
            message: "unlock"
        close_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode doors"
            message: "lock"
#        open_cover:
#          service: lock.unlock
#          entity_id: lock.madoka_door_lock
#        close_cover:
#          service: lock.lock
#          entity_id: lock.madoka_door_lock
      tesla_charge_port_door:
        device_class: door
        friendly_name: "Tesla Charge Port Door"
        value_template: "{{ is_state('sensor.tesla_charge_port_door_open', 'true') }}"
        icon_template: >-
          {% if is_state("sensor.tesla_charge_port_door_open", "true") %}
            mdi:car-door
          {% else %}
            mdi:car-door-lock
          {% endif %}
        open_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode charge_port"
            message: "open"
        close_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode charge_port"
            message: "close"
#        open_cover:
#          service: lock.unlock
#          entity_id: lock.madoka_charger_door_lock
#        close_cover:
#          service: lock.lock
#          entity_id: lock.madoka_charger_door_lock
      tesla_windows:
        device_class: window
        friendly_name: "Tesla Windows"
        value_template: "{{ is_state('sensor.tesla_windows_open', 'true') }}"
        icon_template: >-
          {% if is_state("sensor.tesla_windows_open", "true") %}
            mdi:car-door
          {% else %}
            mdi:car-door-lock
          {% endif %}
        open_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode vent"
            message: "open"
        close_cover:
          service: rest_command.autoremote_phone_command
          data:
            action: "car_mode vent"
            message: "close"

switch:
  - platform: template
    switches:
      tesla_plugged_in:
        friendly_name: Tesla Plugged In
        value_template: "{{ is_state('sensor.tesla_plugged_in', 'true') }}"
        turn_on:
        turn_off:
      tesla_sentry_mode:
        friendly_name: Tesla Sentry Mode
        value_template: "{{ is_state('sensor.tesla_sentry_mode', 'true') }}"
        turn_on:
          - service: rest_command.autoremote_phone_command
            data:
              action: "car_mode sentry_mode"
              message: "on"
        turn_off:
          - service: rest_command.autoremote_phone_command
            data:
              action: "car_mode sentry_mode"
              message: "off"
```
