### DISCUSSION TITLE
Problems installing on Synology Docker

### DISCUSSION THREAD

**Discussion by boba51** [teslamate-org/teslamate#1217] [Q&A] [answered]
Hi, let me start by apologising if this is the wrong place to ask this question, please just redirect to the correct forum.

I've been trying to install Teslamate under Docker running on my Synology box and am running into issues, I'm fairly computer literate working in the IT Industry for many too years, but unfortunately not so much on the Linux/Unix side of things so don't have a good feel for the underlying principles.

Teslamate container crashes with the below in the logs:

ERROR! Config provider Config.Reader failed with:
** (ArgumentError) could not fetch environment variable "DATABASE_USER" because it is not set
    (elixir 1.11.2) lib/system.ex:529: System.fetch_env!/1
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.14) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib 3.14) erl_eval.erl:240: :erl_eval.expr/5
    (stdlib 3.14) erl_eval.erl:232: :erl_eval.expr/5
    (stdlib 3.14) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib 3.14) erl_eval.erl:411: :erl_eval.expr/5
    (elixir 1.11.2) src/elixir.erl:280: :elixir.recur_eval/3
{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.ArgumentError',message=><<"could not fetch environment variable \"DATABASE_USER\" because it is not set">>},[{'Elixir.System','fetch_env!',1,[{file,"lib/system.ex"},{line,529}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,240}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,411}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,280}]}]}}
init terminating in do_boot ({,[{Elixir.System,fetch_env!,1,[{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eva
Crash dump is being written to: erl_crash.dump...done

If I don't use the Host network, the container runs but is constantly looking for the db, I'm assuming because they are not on the same host address and therefore 127.0.0.1 not the same localhost.

I've tried following the Docker install instructions and the related "Idiot's guide to getting this working on a Synology NAS #113" posting to try and modify the settings, but every time there is an issue with the "docker-compose.yml" file.

Any help, pointing the right direction would be appreciated.

Bob

**Comment by DrMichael** [comment]
Apparently DATABASE_USER is not set for the teslamate container?

**Reply by boba51** [reply]
@DrMichael Thanks, but how do I address this, is there something wrong with the image I'm using, other Docker Images/Containers I've used provide everything required for it to work without intervention?

Bob

**Reply by boba51** [reply]
Hi, I've managed to put in the variables from the Docker "docker-compose.yml" section in manually, but now it is waiting for the DB (log below), I've tried to launch the Postgres Container manually but fails, reporting port 5432 in use (I can't see which other installed App is using it)
NB I've tried using the "docker-compose.yml" but keep getting errors when trying to run it and even if I (with your help) get that to run assume the postgres part will fail as above.

Again apologies if this is all basic stuff, I'd love to get Teslamate running on my Synology, but am struggling, been up until 2AM, 2 nights now with nothing to show for it.

waiting for postgres at database:5432 (2sec)
(multiple lines removed)...
waiting for postgres at database:5432 (1024sec)

**Comment by DrMichael** [comment]
What gives `docker-compose logs database`?

Your _docker-compose.yml_ would be helpful...

**Reply by boba51** [reply]
Hi, Apologies if I'm confusing things, I'll try and explain:

In the 1st instance, I want to use the Synology built in Docker Management GUI, but due to issues then tried the "docker-compose.yml" method, unfortunately also without success. 

Synology Docker GUI:
Trying to just use the Docker Images presented to me in the Synology Docker GUI, I was left with just one Container teslamate-teslamate1, which initially had the DATABASE_USER crash 1st mentioned above, then using the GUI I added the variables taken from the "https://docs.teslamate.org/docs/installation/docker" now it's stuck on the latest error "waiting for postgres at database:5432"
I've also launched via the GUI the teslamate-grafana1 container, which apart from changing the local port to 3001 due to clash appears to run OK and I can access its web interface using this port.
Finally I tried to Launch the postgres container from the GUI, this fails with 5432 port clash.

2) I then also tried the docker-compose.yml method, I copied the content from "https://docs.teslamate.org/docs/installation/docker" but keep getting errors when running the "docker-compose up -d" stating something like "/t not support on Line x Column y".

Hopefully that gives you a better idea and where the issues lie which may partly be due to the Synology implementation of Docker but that is the only Docker environment I've ever used and normally it's just a case of Launching the relevant container and it works, perhaps I've been lucky in the past.

Thanks for your continued help.

Bob

**Comment by jeffwrusso** [comment, marked as answer]
Hi Bob,

I have this running on a Synology.  I did run into similar issues trying to use the docker GUI in the Synology.  I ended up deleting everything and starting over.  First, I created a folder on my Synology called "docker", I then created a subfolder called "teslamate" and inside "teslamate" another subfolder called "import". Then I enabled the Text Editor on the Synology (you could use VI if you like) and saved the following docker-compose.yml file to the root of the "docker" folder I created (you would need to update the VIRTUAL_HOST with your Synology‘a local IP address).


```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=192.168.x.x
    ports:
      - 4000:4000
    volumes:
      - ./../docker/teslamate/import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

Next, I logged in via terminal and ran the following:

`mv /volume1/docker/docker-compose.yml /volume1/@docker/docker-compose.yml`

Then `cd volume1/@docker` and finally `docker-compose up -d`

That should create all the dockers and start them up.  You can then see and control them in the docker UI.  I just wouldn't try to upgrade from there.  If you want to upgrade when new versions are released, connect to Synology via terminal go to the "volume1/@docker" folder and run the following: 

`docker-compose down`
`docker-compose pull`
`docker-compose up -d`

Thanks,
Jeff
