### DISCUSSION TITLE
How to set-up 2 TeslaMate instances on a Raspberry Pi?

### DISCUSSION THREAD

**Discussion by fvanson** [teslamate-org/teslamate#1339] [Getting started]
--- updated 2021.02.15 ---
I have currently TeslaMate running on a Raspberry Pi 4 Model B 4GB together with a Samsung T5 SSD with 500GB. I use TeslaMate simultaneously with TeslaFi for our family Tesla Model 3 (still 6 months of subscription to TeslaFi left so that I have time to see whether I like TeslaMate as its replacement or not). TeslaMate is running next to Domoticz and HomeBridge, so there is still a good portion of capacity available on the Raspberry Pi.

I have now ordered also a Tesla Model 3 to replace my current ICE company car, and would like to add it to TeslaMate on the same Raspberry Pi. So this Tesla Model 3 will have another Tesla account. From what I read this is possible, but it would require a second instance of TeslaMate and Grafana to run on the Pi. It is possible to use same Postgres instance but with a separate database, and use the same MQQT broker. I know that this project is not designed around multi-account tool, but it was in several discussions mentioned that it should be possible by running certain programs in parallel via Docker.

Via a Tesla Motors Club thread, I managed to get to the below **docker.compose.yml** file which works partially. It does keep the existing installation alive and running, and some of what is needed works but the needed additional database is not working. Anybody able to help out on what I need to do to get a second instance of TeslaMate running on the same Raspberry Pi?

Thank you in advance for your help!

My docker-compose.yml file is stored in my /home/pi folder, and the content is has evolved now to one as can be seen below:

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  teslamate2:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate2
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto2
    ports:
      - 4001:4000
    volumes:
      - ./import2:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  grafana2:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate2
      - DATABASE_HOST=database
    ports:
      - 3001:3000
    volumes:
      - teslamate-grafana2-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  mosquitto2:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1884:1883
    volumes:
      - mosquitto2-conf:/mosquitto/config
      - mosquitto2-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
  teslamate-grafana2-data:
  mosquitto2-conf:
  mosquitto2-data:
```

With above, the 1st instance of TeslaMate runs without issues.
2nd instance of Grafana can be accessed via <ip-address>:4001
2nd instance of TeslaMate frontend is not available via <ip-address>:3001

When stopping and starting teslamate2 instance, I get following log:

```
pi@raspberrypi:~ $ docker-compose stop teslamate2
Stopping pi_teslamate2_1 ... done
pi@raspberrypi:~ $ docker-compose up teslamate2
Starting pi_teslamate2_1 ... done
Attaching to pi_teslamate2_1
teslamate2_1  | 2021-02-14 08:30:05.207 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:05.207 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:06.910 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:08.050 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:08.138 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate2_1  | 
teslamate2_1  |   * The database does not exist
teslamate2_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate2_1  |     migrations, was defined by another library
teslamate2_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate2_1  |     indexes with a migration_lock)
teslamate2_1  | 
teslamate2_1  | To fix the first issue, run "mix ecto.create".
teslamate2_1  | 
teslamate2_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate2_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate2_1  | another table and/or repository for managing migrations:
teslamate2_1  | 
teslamate2_1  |     config :teslamate, TeslaMate.Repo,
teslamate2_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate2_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate2_1  | 
teslamate2_1  | The full error report is shown below.
teslamate2_1  | 
teslamate2_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2958ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate2_1  | 
teslamate2_1  |   1. Tracking down slow queries and making sure they are running fast enough
teslamate2_1  |   2. Increasing the pool_size (albeit it increases resource consumption)
teslamate2_1  |   3. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate2_1  | 
teslamate2_1  | See DBConnection.start_link/2 for more information
teslamate2_1  | 
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate2_1  |     (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:838: Ecto.Adapters.SQL.execute_ddl/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:669: Ecto.Migrator.verbose_schema_migration/3
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:498: Ecto.Migrator.lock_for_migrations/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:413: Ecto.Migrator.run/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:145: Ecto.Migrator.with_repo/3
teslamate2_1  |     (teslamate 1.21.3) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate2_1  | 2021-02-14 08:30:12.125 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:12.126 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:14.790 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:14.832 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:15.044 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate2_1  | 
teslamate2_1  |   * The database does not exist
teslamate2_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate2_1  |     migrations, was defined by another library
teslamate2_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate2_1  |     indexes with a migration_lock)
teslamate2_1  | 
teslamate2_1  | To fix the first issue, run "mix ecto.create".
teslamate2_1  | 
teslamate2_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate2_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate2_1  | another table and/or repository for managing migrations:
teslamate2_1  | 
teslamate2_1  |     config :teslamate, TeslaMate.Repo,
teslamate2_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate2_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate2_1  | 
teslamate2_1  | The full error report is shown below.
teslamate2_1  | 
teslamate2_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2953ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate2_1  | 
teslamate2_1  |   1. Tracking down slow queries and making sure they are running fast enough
teslamate2_1  |   2. Increasing the pool_size (albeit it increases resource consumption)
teslamate2_1  |   3. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate2_1  | 
teslamate2_1  | See DBConnection.start_link/2 for more information
teslamate2_1  | 
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate2_1  |     (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:838: Ecto.Adapters.SQL.execute_ddl/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:669: Ecto.Migrator.verbose_schema_migration/3
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:498: Ecto.Migrator.lock_for_migrations/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:413: Ecto.Migrator.run/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:145: Ecto.Migrator.with_repo/3
teslamate2_1  |     (teslamate 1.21.3) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
pi_teslamate2_1 exited with code 1
teslamate2_1  | 2021-02-14 08:30:19.347 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:19.347 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:20.626 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:21.389 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:22.233 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate2_1  | 
teslamate2_1  |   * The database does not exist
teslamate2_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate2_1  |     migrations, was defined by another library
teslamate2_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate2_1  |     indexes with a migration_lock)
teslamate2_1  | 
teslamate2_1  | To fix the first issue, run "mix ecto.create".
teslamate2_1  | 
teslamate2_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate2_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate2_1  | another table and/or repository for managing migrations:
teslamate2_1  | 
teslamate2_1  |     config :teslamate, TeslaMate.Repo,
teslamate2_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate2_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate2_1  | 
teslamate2_1  | The full error report is shown below.
teslamate2_1  | 
teslamate2_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2911ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate2_1  | 
teslamate2_1  |   1. Tracking down slow queries and making sure they are running fast enough
teslamate2_1  |   2. Increasing the pool_size (albeit it increases resource consumption)
teslamate2_1  |   3. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate2_1  | 
teslamate2_1  | See DBConnection.start_link/2 for more information
teslamate2_1  | 
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate2_1  |     (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:838: Ecto.Adapters.SQL.execute_ddl/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:669: Ecto.Migrator.verbose_schema_migration/3
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:498: Ecto.Migrator.lock_for_migrations/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:413: Ecto.Migrator.run/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:145: Ecto.Migrator.with_repo/3
teslamate2_1  |     (teslamate 1.21.3) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
pi_teslamate2_1 exited with code 0
teslamate2_1  | 2021-02-14 08:30:26.197 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:26.198 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:28.445 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:28.866 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate2" does not exist
teslamate2_1  | 2021-02-14 08:30:29.140 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate2_1  | 
teslamate2_1  |   * The database does not exist
teslamate2_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate2_1  |     migrations, was defined by another library
teslamate2_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate2_1  |     indexes with a migration_lock)
teslamate2_1  | 
teslamate2_1  | To fix the first issue, run "mix ecto.create".
teslamate2_1  | 
teslamate2_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate2_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate2_1  | another table and/or repository for managing migrations:
teslamate2_1  | 
teslamate2_1  |     config :teslamate, TeslaMate.Repo,
teslamate2_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate2_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate2_1  | 
teslamate2_1  | The full error report is shown below.
teslamate2_1  | 
teslamate2_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2959ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate2_1  | 
teslamate2_1  |   1. Tracking down slow queries and making sure they are running fast enough
teslamate2_1  |   2. Increasing the pool_size (albeit it increases resource consumption)
teslamate2_1  |   3. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate2_1  | 
teslamate2_1  | See DBConnection.start_link/2 for more information
teslamate2_1  | 
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate2_1  |     (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:838: Ecto.Adapters.SQL.execute_ddl/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:669: Ecto.Migrator.verbose_schema_migration/3
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:498: Ecto.Migrator.lock_for_migrations/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:413: Ecto.Migrator.run/4
teslamate2_1  |     (ecto_sql 3.5.4) lib/ecto/migrator.ex:145: Ecto.Migrator.with_repo/3
teslamate2_1  |     (teslamate 1.21.3) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
pi_teslamate2_1 exited with code 1
```

So the issue appears to be the creation of the 2nd database next to the database used for the 1st instance of TeslaMate. From what I believe to understand - being new to the Raspberry Pi environment - the definition of the database is in an old format of Ecto, but I have no clue how to run the mentioned commands 'mix ecto.create' and 'mix ecto.drop'. I have tried even a second database definition in the docker-compose.yml, but also that did not work. So I start to get stuck.

Would love to get a 2nd instance of TeslaMate running on 1 Raspberry Pi as it keeps environmental footprint small; no additional Raspberry Pi + SSD, and not a 2nd Pi running 24/7.

Thank you in advance for your hints, answers, etc.

**Comment by fvanson** [comment]
I am giving up on this option, so I will go for a 2nd Raspberry Pi 4 Model B with a Samsung T5 SSD as I do not believe that it is possible to have 2 instances via Docker running 1 Raspberry Pi.

**Reply by snicoll** [reply]
Why don't you have two docker-compose files? Each file would have their own network and then you need to make sure the exposed ports don't clash.

**Reply by fvanson** [reply]
Thank you @snicoll !!! After fiddling a little around I got it working! Let me share my steps and things which did not work for those who want to do the same.

I first tried to rename the docker-compose.yml file in the home folder for the first Tesla & Tesla account to docker-compose-1.yml, and create a new docker-compose-2.yml in the same home folder for the second Tesla & Tesla account. But with this both docker-compose files became disabled to be executed from the terminal.

As a next try I kept the docker-compose.yml for the first Tesla & Tesla account in the home folder, and created in a separate folder (TeslaMate2) the docker-compose.yml for the second Tesla & Tesla account. And that did the job. Just to be sure I also defined a separate database for the 2nd Tesla & Tesla account.

So in my home directory I had following content in the docker-compose.yml:
```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

In the directory TeslaMate2 I have created a docker-compose.yml file with following content:
```
version: "3"

services:
  teslamate2:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate2
      - DATABASE_HOST=database2
      - MQTT_HOST=mosquitto2
    ports:
      - 4001:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database2:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate2
    volumes:
      - teslamate-db2:/var/lib/postgresql/data

  grafana2:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate2
      - DATABASE_HOST=database2
    ports:
      - 3001:3000
    volumes:
      - teslamate-grafana2-data:/var/lib/grafana

  mosquitto2:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1884:1883
    volumes:
      - mosquitto2-conf:/mosquitto/config
      - mosquitto2-data:/mosquitto/data

volumes:
  teslamate-db2:
  teslamate-grafana2-data:
  mosquitto2-conf:
  mosquitto2-data:
```

And with that I got 2 instances of TeslaMate working on 1 Raspberry Pi. I can now access both Tesla's via following url's from a browser:
* TeslaMate front end: Tesla 1 = http://< ip-address >:4000, Tesla 2 = http://< ip-address >:4001
* Grafana: Tesla 1 = http://< ip-address >:3000, Tesla 2 = http://< ip-address >:3001

One tweak I can suggest in case you want to import data from for instance TeslaFi into TeslaMate. Please run in a terminal "sudo chmod 777 import" in both home folder as in the folder in which the docker-compose.yml of the 2nd Tesla is located. If you do not do this, then you are not able to import TeslaFi data put in the import folder ... at least that happened to me.
