### DISCUSSION TITLE
Teslamate on Docker Swarm

### DISCUSSION THREAD

**Discussion by tgerighty** [teslamate-org/teslamate#1825] [Q&A]
Hi,

Been running Teslamate for many months now on docker. Want to move it to a new docker swarm cluster.

Mosquitto, Postgres and Grafana all run fine but I can't get Teslamate to run. Running on a node directly using the original docker-compose works so its clearly the move to swarm which causes the problem. Partially this is because I have to use bind mounts and not docker volumes. I also changed the references to the containers to be explicit to IP of the swarm head node.

I've modified the docker-compose to the following

````
version: "3.4"

services:
  teslamate:
    image: teslamate/teslamate:latest
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=192.168.55.70
      - MQTT_HOST=192.168.55.70
      - PUID=1025
      - PGID=100
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
      - PUID=1025
      - PGID=100
    volumes:
      - /mnt/docker/teslamate/db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=192.168.55.70
      - PUID=1025
      - PGID=100
    ports:
      - 3010:3000
    volumes:
      - /mnt/docker/teslamate/grafana:/var/lib/grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mosquitto:
    image: eclipse-mosquitto:2
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    environment:
      - PUID=1025
      - PGID=100
    volumes:
      - /mnt/docker/teslamate/mosquitto:/mosquitto/config
      - /mnt/docker/teslamate/mosquitto:/mosquitto/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
```

The teslamate container either gets stuck in preparing or rejected with a bind error for a volume I don't have in the config:

`invalid mount config for type "bind": bind source path does not exist: /data/compose/26/import`

Database is up:
`2021-07-11 09:12:26.548 UTC [1] LOG:  database system is ready to accept connections`
Mosquitto is up:
`1625994732: mosquitto version 2.0.11 running`

any ideas?
