### DISCUSSION TITLE
During Docker install, Postgresql will not initialise database or user

### DISCUSSION THREAD

**Discussion by aean0x** [teslamate-org/teslamate#2271] [Getting started]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running Raspbian Buster on an RPi4, docker-compose version  1.21.0-3.

No error dialogue on docker-compose up -d

Teslamate logs state unable to connect to Postgresql database (see log output).

During troubleshooting, downed all containers and deleted volumes numerous times to ensure a fresh start.

The solution: Logged into shell in Postgresql to discover no users or db created, unable to create manually due to no roles specified for any user in the container. Opted to place the commands from the manual Debian install instructions in /docker-entrypoint-initdb.d/init.sql which was executed on restart, fixing this issue. Teslamate is now connecting on socket 4000 and functional.

Given my limited experience with Docker and Postgresql, I don't have any working theories of why the yml didn't do its job. Postgresql's documentation seems to back up that it should have worked & had correct syntax. Something different about Raspbian, I guess.

### Steps To Reproduce

Running `docker-compose up -d` with the Docker instructions on teslamate.org

### Relevant log output

```shell
2021-12-17 17:43:10.614 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate" does not exist
2021-12-17 17:43:10.614 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate" does not exist
2021-12-17 17:43:12.705 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "teslamate" does not exist
2021-12-17 17:43:13.554 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :teslamate, TeslaMate.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2956ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:678: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:504: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    (teslamate 1.25.0) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
```

### Type of installation

Docker

### Version

v1.25.0

**Comment by AlexArlievsky** [comment]
same problem here

**Comment by Dulanic** [comment]
Provide logs of db and your docker-compose.yml.

**Reply by AlexArlievsky** [reply]
Problem resolved after adding  - DATABASE_POOL_SIZE=10 to teslamate service definition in docker-compose.yml.

Original file:

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto

    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

```
Do you still need logs ? Then I'll have to get instructions how to reproduce the problem without loss of the accumulated data.
