### DISCUSSION TITLE
QNAP NAS Container Station Setup

### DISCUSSION THREAD

**Discussion by Airosus** [teslamate-org/teslamate#2318] [Getting started]
I wasn't able to find any step-by-step guide for setting up Teslamate on a QNAP NAS on Github or elsewhere online. I found two youtube videos (one in Italian and one in Spanish) where I followed along as best as I could.

(videos for reference)
https://www.youtube.com/watch?v=raqWC4gnVtA and https://www.youtube.com/watch?v=k3OILXU0ofY

I was able to follow along until I got to the login step where you click a link within the Container Station app on the QNAP to log into Teslamate. The tesla_teslamate_1 container does not have a link icon in Container Station to direct me to a login page. I also noticed that the "tesla_database_1" container is not running, while the other three containers are. Also, the "tesla_grafana_1" container has an available link to log in, but I don't know what credentials to use. See the attached image for the current status. 
<img width="1474" alt="Teslamate issue" src="https://user-images.githubusercontent.com/62717804/149573556-c25a49ba-88ef-4b6b-9fe6-72efcdc9ec77.png">

I am pretty new to using Docker and managing a NAS, so simple terminology and clear step-by-step instructions are very appreciated!

**Comment by metawatchkalle** [comment]
Same problem. Restarting the whole Qnap-NAS solved the problem temporarily. After restarting, the links appear for a few days. But after a few days the database disconnects and i have to restart the NAS once again. I use a TS-231P. I think there is a performance issue with this type of Qnap.

**Comment by Airosus** [comment]
So is this just a matter of the low-end/low-performance QNAP not being able
to support and properly run teslamate? Should I just buy/set up a raspberry
pi to run this?

**Comment by chkeith1** [comment]
Running on a TS-230 without any issue so it should not be a low-end performance problem.
Try reinstalling it maybe?
Or try this as this works for me

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      
   volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```
