### DISCUSSION TITLE
grafana restarting

### DISCUSSION THREAD

**Discussion by gjuecat** [teslamate-org/teslamate#2542] [Q&A]
Do I need grafana & mosquitto in this container? I'm running on debian with a local installation of latest grafana & mosquitto.

I tried the docker version of teslamate and did some local volume and ports adjustments. After starting the YML file everything is up except grafana, it's alway restarting.

docker-compose.yml
```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=ThisIsMySecureTesl@m@teP@ssword
      - DATABASE_USER=teslamate
      - DATABASE_PASS=myPassword
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4045:4000
    volumes:
      - /home/docker/YAML/import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=myPassword
      - POSTGRES_DB=teslamate
    volumes:
      - /home/docker/YAML/teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=myPassword
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3045:3000
    volumes:
      - /home/docker/YAML/teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1845:1883
    volumes:
      - /home/docker/YAML/mosquitto-conf:/mosquitto/config
      - /home/docker/YAML/mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

Using docker compose version 2.3.3
