### DISCUSSION TITLE
No data in Grafana, TeslaMate unaccessible

### DISCUSSION THREAD

**Discussion by GitHub-erNik** [teslamate-org/teslamate#2668] [General]
I run into some problems with TeslaMate lately on my Synology NAS with Container. I reinstalled already couple of times. After this re-installation, it is always working and then - me randomly want to look up some data - it fails to do so.

- Grafana is loading the UI, but no data is accessible. Loads and loads without result
- :4000 for TeslaMate configuration was still accessible then I restarted the container. Now unaccessible.

Just don't know what I do wrong. I post some Screenshots. Any help is highly appricated.

Protocol for TeslaMate container says: "waiting for postgres at database:5432"

![Docker](https://user-images.githubusercontent.com/106312055/170892253-977b47c8-1db0-4b9a-b050-8de89b56ec16.jpg)
![Grafana](https://user-images.githubusercontent.com/106312055/170892255-8eb0d7e0-e0a5-4cb4-834e-ff64bc50fa9b.jpg)
![TeslaMate](https://user-images.githubusercontent.com/106312055/170892256-464f3925-78df-4356-ab41-bf345142e01c.jpg)

**Comment by GitHub-erNik** [comment]
![teslamate_1_Überblick](https://user-images.githubusercontent.com/106312055/170892335-d8b0c81e-3f04-4488-a08c-8ab6623a09f6.jpg)
![teslamate_1_Volume](https://user-images.githubusercontent.com/106312055/170892336-176c0767-ebe2-4974-871e-2009c73a9331.jpg)

**Reply by buzzhd** [reply]
Don't use the latest yml, but use the old version if you can find one. I had same issue but no one could ever tell me how to solve the problem. Then on a hunch, I used back the old version and it worked.

**Reply by GitHub-erNik** [reply]
Ohh.. thanks for this advice. I try to find the old version. Myself don't have it anymore since I moved it to the @docker folder for running it. After this it was no longer there, so I had to create a new one and oriented myself on the official documentation (https://docs.teslamate.org/docs/installation/docker/)

I have this content in my file:

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=MYKEY
      - DATABASE_USER=teslamate
      - DATABASE_PASS=MYPASS
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=MYPASS
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=MYPASS
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```
Can u maybe post ur code here, so that  can compare it, @buzzhd ?
