### DISCUSSION TITLE
Documentation for integration with HomeAssistant is outdated.

### DISCUSSION THREAD

**Discussion by star114** [teslamate-org/teslamate#2702] [General]
Hello,

I’m not sure this is proper place and may someone already reported this issue, but I’ll share the recent home assistant breaking changes regarding mqtt from 2022.06 version.

[Teslamate documentation](https://docs.teslamate.org/docs/integrations/home_assistant) has outdated examples at the moment.
Please check this link: [HomeAssistant 2022.06 breaking changes](https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes)

**Here’s copy from the link.**

_Defining manually configured MQTT entities directly under the respective platform keys (e.g., fan, light, sensor, etc.) is deprecated, and support will be removed in Home Assistant Core 2022.9._

_Manually configured MQTT entities should now be defined under the mqtt configuration key in configuration.yaml instead of under the platform key._

_As an example, this is now deprecated:_

```
sensor:
  - platform: "mqtt"
    name: "My sensor"
    state_topic: "some-state-topic"
```

_The configuration needs to be updated to this format:_

```
mqtt:
  sensor:
    - name: "My sensor"
      state_topic: "some-state-topic"
```
