### DISCUSSION TITLE
Backing up database when not using docker-compose

### DISCUSSION THREAD

**Discussion by jdhorner** [teslamate-org/teslamate#2742] [Q&A] [answered]
I've recently migrated a bunch of my docker setups to one central instance of Portainer, with different stacks grouping my containers into purpose. For example, my new Tesla stack runs teslamate, grafana, postgres, and mosquitto. I used to have all that in a docker-compose file, but obviously, that's no longer needed with the new setup. So now, when I run the standard command to create a backup file: 
```
❯ sudo docker-compose exec -T postgres pg_dump -U teslamate teslamate > ./teslamate.bck2
```
I get an error: 
```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```
This is obviously because I don't have a docker-compose.yml file any more. I tried changing it to just use docker, with the lower-case T option: 
```
❯ sudo docker exec -t postgres pg_dump -U teslamate teslamate > ./teslamate.bck2
```
But that also doesn't work. It just exports the dump script itself into the backup file, instead of the actual DB "doing" stuff. 

What's the right way to create a backup if I'm not using docker-compose? I thought it would be easy, but I'm obviously missing something. Thanks very much!

**Comment by DrMichael** [comment, marked as answer]
> This is obviously because I don't have a docker-compose.yml file any more. I tried changing it to just use docker, with the lower-case T option:
> 
> ```
> ❯ sudo docker exec -t postgres pg_dump -U teslamate teslamate > ./teslamate.bck2
> ```
> 
> But that also doesn't work. It just exports the dump script itself into the backup file, instead of the actual DB "doing" stuff.
> 
> What's the right way to create a backup if I'm not using docker-compose? I thought it would be easy, but I'm obviously missing something. Thanks very much!

You need to use the container id instead of "postgres".

**Reply by jdhorner** [reply]
Strange. It still didn't work, but it didn't work in a new way. This time there was _some_ data exported, but it still just basically dumped the pg_dump script into a text file called teslamate.bck2 instead of filling it with data. 

I can always quickly tell because my current backup is around 650 MB, and it's only dumping around a single MB each time, now.

**Reply by jdhorner** [reply]
Going into Grafana now, I see that something wrong has happened. :/ 

I had been under the impression that my database was saved as a local file on my docker host machine, mapped in the config file. But I see now it's a volume specified within the config. So I'm actually glad I have a backup! I need to restore my previous data into this new database. But I guess that's beyond the scope of this discussion. (I'm also guessing I can't merge the past day or two of data with my old data? Which is fine; I'd rather have the old data and lose just the last day or two) 


```yml
version: "3"

services:
  teslamate:
    container_name: teslamate
    image: teslamate/teslamate:latest
    restart: unless-stopped
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=[masked]
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=postgres
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - /home/ubuntu/volumes/teslamate/import:/opt/app/import
    cap_drop:
      - all

  postgres:
    container_name: postgres
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=[masked]
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data  // <-- like an idiot, I thought this was local. But it's a docker-managed volume. 
      
  grafana:
    container_name: grafana
    image: teslamate/grafana:latest
    restart: unless-stopped
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=[masked]
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=postgres
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```
