### DISCUSSION TITLE
Add Tire Sensors to Home Assist

### DISCUSSION THREAD

**Discussion by Corrugator** [teslamate-org/teslamate#2837] [Q&A]
Hi,

is there a way to add the Tire Sensors to teslamate in Home Assist.

Maybe only input the Sensors in the sensors + mqqtsensors.yaml ?

**Comment by DarrenEwaniuk** [comment]
The default is pressure in bar.  If that's what you need, you just need mqtt_sensors.yaml
If you want PSI, then also add the template sensors in your sensors.yaml

In mqtt_sensors.yaml:
```yaml
- name: Tesla tpms front left
  state_topic: "teslamate/cars/1/tpms_pressure_fl"
  unit_of_measurement: "bar"
  icon: mdi:car-tire-alert

- name: Tesla tpms front right
  state_topic: "teslamate/cars/1/tpms_pressure_fr"
  unit_of_measurement: "bar"
  icon: mdi:car-tire-alert

- name: Tesla tpms rear left
  state_topic: "teslamate/cars/1/tpms_pressure_rl"
  unit_of_measurement: "bar"
  icon: mdi:car-tire-alert

- name: Tesla tpms rear right
  state_topic: "teslamate/cars/1/tpms_pressure_rr"
  unit_of_measurement: "bar"
  icon: mdi:car-tire-alert
```

In sensors.yaml:
```
- platform: template
  sensors:
    tesla_tpms_front_left_psi:
      value_template: '{{ (states.sensor.tesla_tpms_front_left.state |float * 14.504) | round(1) }}'
      unit_of_measurement: 'psi'
      icon_template: mdi:car-tire-alert

    tesla_tpms_front_right_psi:
      value_template: '{{ (states.sensor.tesla_tpms_front_right.state |float * 14.504) | round(1) }}'
      unit_of_measurement: 'psi'
      icon_template: mdi:car-tire-alert
        
    tesla_tpms_rear_left_psi:
      value_template: '{{ (states.sensor.tesla_tpms_rear_left.state |float * 14.504) | round(1) }}'
      unit_of_measurement: 'psi'
      icon_template: mdi:car-tire-alert

    tesla_tpms_rear_right_psi:
      value_template: '{{ (states.sensor.tesla_tpms_rear_right.state |float * 14.504) | round(1) }}'
      unit_of_measurement: 'psi'
      icon_template: mdi:car-tire-alert
```
