### DISCUSSION TITLE
Best Practice: A second Grafana and Mosquitto?

### DISCUSSION THREAD

**Discussion by instantdreams** [teslamate-org/teslamate#2932] [Q&A]
I run Teslamate using a docker-compose very similar to the default example. The structure of the compose file includes containers for teslamate, a specific version of grafana for teslamate, and standard versions of postgres & mosquitto.

On the same server running my Teslamate container stack I'd like to have an additional Grafana container so I could create and manage some dashboards from the prometheus time series database collecting information on this server. I'd also like a separate mosquitto container to separate it from Teslamate as I wish to use it for NodeRED, Frigate, and HomeAssisstant.

Is there a best practice for this?

My thoughts are:
* Remove mosquitto from the teslamate compose file
* Create a separate mosquitto container using default port 1883
* Amend teslamate compose file so grafana uses port 3001:3000
* Amend teslamate configuration to amend the dashboards URL to be http://[server]:3001
* Create a separate grafana container using default port 3000

This way, mosquitto would be separate and can be used by other containers including Teslamate, and port 3000 can be used by a default Grafana install.

Would this work? Is it a best practice? Thanks!

**Comment by instantdreams** [comment]
Anyone got any experience with this approach?

**Reply by andrewjw** [reply]
I can't really comment on Mosquitto, but for Grafana I run my own instance and use provisioning to load the Teslamate dashboards, along side my own.

In case it's useful here's my docker compose file:
```
grafana:
    image: grafana/grafana:8.3.4
    container_name: grafana
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./teslamate/grafana/dashboards:/teslamate
    environment:
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel
      - GF_ANALYTICS_REPORTING_ENABLED=FALSE
      - DATABASE_PORT=5433
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_DISABLE_GRAVATAR=true
    ports:
      - 3000:3000
```
      
In ./grafana/provisioning/dashboards/teslamate.yml I have:
```
apiVersion: 1

providers:
  # <string> an unique provider name. Required
  - name: 'TeslaMate'
    orgId: 1
    # <string> name of the dashboard folder.
    folder: 'TeslaMate'
    # <string> folder UID. will be automatically generated if not specified
    folderUid: 'bIREOoIMz'
    # <string> provider type. Default to 'file'
    type: file
    # <bool> disable dashboard deletion
    disableDeletion: false
    # <bool> enable dashboard editing
    editable: false
    # <int> how often Grafana will scan for changed dashboards
    updateIntervalSeconds: 10
    # <bool> allow updating provisioned dashboards from the UI
    allowUiUpdates: false
    options:
      # <string, required> path to dashboard files on disk. Required when using the 'file' type
      path: /teslamate
      # <bool> use folder names from filesystem to create folders in Grafana
      foldersFromFilesStructure: false
```
     
Finally I have the TeslaMate git repo checked out so the dashboards appear in /teslamate on the Grafana container.
     
Hope that helps.
Andrew
