### DISCUSSION TITLE
Help upgrading from 1.26.1 to 1.27.1

### DISCUSSION THREAD

**Discussion by tesla2021a** [teslamate-org/teslamate#2996] [Q&A] [answered]
Hi, I'm at 1.26.1 with Postgres at 13 and Mosquito at 2 in a docker environment on Rasbian 32 bit version of Buster (V10). Whenever I try to update to 1.27.1 (latest), I lose all my data (Grafana shows 'No Data'). I followed this link to upgrade Postgres to 14 and still can't get it work to work :-(

https://docs.teslamate.org/docs/maintenance/upgrading_postgres/

Cleaning everything (docker image rm, container rm, volume rm and prune everything), then reinstalling 1.26.1 followed by a backup restore brings everything back but of course, stuck at 1.26.1.

Even a clean installation of 1.27.1 with Postgres 14 followed by a restoration of the 1.26 data (that was with postgres at 13) do not work (again, No Data).

What am I missing to successfully upgrade to 1.27.1? 

Thanks.

**Comment by tesla2021a** [comment]
Update: Upgrading to Postgres 14 while at 1.26.1 still had all the data. Only once I upgraded 1.26.1 to 1.27.1 did the data disappear. Going back to 1.26.1 (but staying at Postgres 14) brought the data back. This is what my docker-compose.yml file looks like
```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:1.26.1
    restart: always
    environment:
      - ENCRYPTION_KEY=GupjEMK0bGVzgTdQ MY KEY LOOKS LIKE THIS GNrrOXJvgKpvF+x6N1JBn6g4Gq+
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - CHECK_ORIGIN=true
      - TZ=${TM_TZ}
    volumes:
      - ./import:/opt/app/import
    ports:
      - 4000:4000
    cap_drop:
      - all

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:1.26.1
    restart: always
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

This is my .env file
```
TM_DB_USER=teslamate
TM_DB_PASS=*****
TM_DB_NAME=teslamate

GRAFANA_USER=admin
GRAFANA_PW=*****

FQDN_GRAFANA=grafana.*****.duckdns.org
FQDN_TM=teslamate.*****.duckdns.org

TM_TZ=America/Montreal

LETSENCRYPT_EMAIL=*****@gmail.com
```

Is there something wrong in those files? My installation sit behinds a Apache proxy with a letsencrypt certificate.
