### DISCUSSION TITLE
Self using teslamate MQTT broker

### DISCUSSION THREAD

**Discussion by ernesst** [teslamate-org/teslamate#3094] [Q&A]
Hello, 

I would like to use the MQTT broker within Teslamate docker for my home automation purpose. 
So far everything works well, all my IOT sensors are passing through the Teslamate MQTT then topic are read by my automation server such as home assistant. 
The only one I cannot figure out to publish its information through this MQTT broket is teslamate ifself :/ 

```
 GNU nano 4.8                                                                                    docker-compose.yml                                                                                               
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:edge
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=127.0.0.1
```
I've tried several server host address, the only one that teslamate doesn't complain is mosquitto ... but then I cannot see the topics via  `mosquitto_sub -h 127.0.0.1 -t "teslamate/cars/1/" `
While I can see the other publishers topics without issue. 

What I'm missing to enable teslamate to publish mqtt data into it's own docker mqtt server ?

Thanks !
