### DISCUSSION TITLE
Teslamate <> Home assistant

### DISCUSSION THREAD

**Discussion by El-Daron** [teslamate-org/teslamate#3240] [Q&A]
Hello,

Stuck here with this automation in Home Assistant:

```
- alias: Open garage if car returns home
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.tesla_location
      from: "not_home"
      to: "home"
  condition:
    - condition: state
      entity_id: sensor.tesla_state
      state: driving
  action:
    - service: cover.open_cover
      entity_id: cover.garage_door
``` 

For un unknown reason, it works without the condition, but i can't find where i did a mistake here.

Thank you for help :)
