### DISCUSSION TITLE
Starting a 2nd docker container issues

### DISCUSSION THREAD

**Discussion by mtrujilloariza** [teslamate-org/teslamate#3302] [Getting started]
Hi I'm trying to run a second instance of tesla mate for a different account with the following docker file: 
version: "3"

```
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=${ENC_KEY}
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${DB_PASS}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4001:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS={DB_PASS}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3001:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1884:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

grafana is able to load up, but when i try to open tesla mate nothing happens. Looking at the logs it seems to be a password issues

teslamate 

```
  1. Ensuring your database is available and that you can connect to it

  2. Tracking down slow queries and making sure they are running fast enough

  3. Increasing the pool_size (although this increases resource consumption)

  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval


See DBConnection.start_link/2 for more information


    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1

    (elixir 1.15.0-rc.1) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2

    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4

    (ecto_sql 3.10.1) lib/ecto/migrator.ex:738: Ecto.Migrator.verbose_schema_migration/3

    (ecto_sql 3.10.1) lib/ecto/migrator.ex:552: Ecto.Migrator.lock_for_migrations/4

    (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4

    (ecto_sql 3.10.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3

    nofile:1: (file)

2023-07-31 22:55:39.688 [error] Postgrex.Protocol (#PID<0.172.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"

2023-07-31 22:55:39.688 [error] Postgrex.Protocol (#PID<0.173.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"

2023-07-31 22:55:41.556 [error] Postgrex.Protocol (#PID<0.172.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"

2023-07-31 22:55:42.006 [error] Postgrex.Protocol (#PID<0.173.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"

2023-07-31 22:55:42.550 [error] Could not create schema migrations table. This error usually happens due to the following:


  * The database does not exist

  * The "schema_migrations" table, which Ecto uses for managing

    migrations, was defined by another library

  * There is a deadlock while migrating (such as using concurrent

    indexes with a migration_lock)


To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.


To address the second, you can run "mix ecto.drop" followed by

"mix ecto.create", both for the desired MIX_ENV. Alternatively you may

configure Ecto to use another table and/or repository for managing

migrations:


    config :teslamate, TeslaMate.Repo,

      migration_source: "some_other_table_for_schema_migrations",

      migration_repo: AnotherRepoForSchemaMigrations


The full error report is shown below.


** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2927ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
```

teslamate postgress:

```

2023-07-31 22:59:01.214 UTC [191] FATAL:  password authentication failed for user "teslamate"

2023-07-31 22:59:01.214 UTC [191] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"

2023-07-31 22:59:01.287 UTC [192] FATAL:  password authentication failed for user "teslamate"

```

I also have this docker file in a different directory than my other instance.

any help will be appreciated. Thank you
