### DISCUSSION TITLE
How can you move the volumes to actual bind mounts so it's easier to move teslamate to a new docker instance?

### DISCUSSION THREAD

**Discussion by pcm1ke** [teslamate-org/teslamate#3352] [Q&A]
I'm running into an issue where I need to migrate my docker instance from one host to another. All my other docker containers have their "data" stored outside of docker on actual volumes that exist outside of docker; teslamate is the only one that's using docker named volumes. How can I change this without things breaking?

I tried simply copying the data out from the /var/lib/docker/volumes/ and putting it somewhere on the host and then changing the named volumes to actual mount points, but this failed. Specifically postgres failed to work and subsequently so did grafana. The permissions/ownership on the directions I copied over were identical, so I'm not sure why simply changing the location of these volumes matters? I even tried adding "external: true" to the named volumes in the "volumes:" declaration, but that didn't solve it either.

Again, I just want to change the volumes from being named volumes and managed by docker, to actual mount points on the local host so I can easily copy the data from one host to another and just spin teslamate backup with compose.

Thank you in advance!

**Comment by pcm1ke** [comment]
I tried.. no matter what I do, for some reason grafana will not function using a bind mount for it's data. I ended up having to use docker volumes again on the new host. Is there really no way to come off the docker volumes? They make moving from host to host quite annoying to say the least.

**Reply by xamyp** [reply]
Hello, this works with bind volumes. here is an example : 
```yaml
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY= #insert a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS= #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - /home/docker/teslamate/import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD= #insert your secure database password!
      - POSTGRES_DB=teslamate
    volumes:
      - /home/docker/teslamate/postgres/data:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS= #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - /home/docker/teslamate/grafana:/var/lib/grafana #sudo chmod 777 /home/docker/teslamate/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - /home/docker/teslamate/mosquitto/config:/mosquitto/config
      - /home/docker/teslamate/mosquitto/data:/mosquitto/data
```
Don't forget to restart your grafana container after `sudo chmod 777 /home/docker/teslamate/grafana`
