### DISCUSSION TITLE
ERROR: invalid reference format

### DISCUSSION THREAD

**Discussion by exixia** [teslamate-org/teslamate#3545] [Q&A] [answered]
The current version is 1.27.3. An error occurred while updating to the latest version. Seeking assistance
![Jietu20231205-092825](https://github.com/teslamate-org/teslamate/assets/37772580/5a26b904-23a4-49db-91a0-a00ab5f7af45)

**Comment by parkr** [comment]
Something is wrong with your docker-compose.yaml file, specifically the mosquitto image name. Can you paste the contents of that file, redacting any passwords?

**Reply by exixia** [reply]
Thank you very much, I will upload my file, please help me take a look at it."

Feel free to upload your file, and I'll assist you with it.This is docker-compose.yml,docker-compose.yaml is blank。
[docker-compose.txt](https://github.com/teslamate-org/teslamate/files/13554365/docker-compose.txt)

**Reply by exixia** [reply]
Can you help me？Thanks

**Comment by DrMichael** [comment, marked as answer]
Why do you not use the in https://docs.teslamate.org/docs/installation/docker recommended mosquito configuration?
```
  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

```
For questions, how to configure mosquitto, this is not the right place.
