### DISCUSSION TITLE
Consider adding `HEALTHCHECK` to Dockerfile

### DISCUSSION THREAD

**Discussion by SaswatPadhi** [teslamate-org/teslamate#3963] [Ideas]
Hi,
I use an automation to monitor the health of all my running containers. `docker ps` for example shows the health status for currently running containers. However, no status is currently displayed for my teslamate container.
Please consider adding a [`HEALTHCHECK` instruction](https://docs.docker.com/reference/dockerfile/#healthcheck) in teslamate's Dockerfile.

A super simple health check could be just to `curl` port 4000 and see if the server is running (return code 200). But a better health check would be to somehow detect if teslamate is in an error state (either API keys are not configured, or no longer work, or the API is currently unavailable etc). I'm fairly new to this code base though, and am not sure how to query this.

**Comment by cusooner** [comment]
Here is a little workaround in the meantime:

instead of "image", use "build" in your docker-compose.yml

```
    build: 
      dockerfile: Dockerfile.teslamate
```
and add the healthcheck section to the teslamate service:
```
    healthcheck:
      test: curl --fail http://localhost:4000 || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
```

additionally, create` Dockerfile.teslamate`:

```
FROM teslamate/teslamate:latest

USER root
RUN apt-get update && apt-get install -y --no-install-recommends curl 
USER nonroot:nonroot
```

The build is needed since the original Dockerfile does not include curl.

**Comment by SaswatPadhi** [comment]
@cusooner Yes, I use a similar workaround for now. To avoid a build, I use `nc` instead:

```yaml
    healthcheck:
      test: "nc -z localhost 4000"
      interval: 15s
      timeout: 2s
      start_period: 60s
```

but this would only check if the port is "open". Your workaround would additionally check if the port is serving HTTP successfully.
