### DISCUSSION TITLE
Where to update <your tesla model> in mqtt_sensors.yaml

### DISCUSSION THREAD

**Discussion by stauffenberg2020** [teslamate-org/teslamate#4351] [Q&A] [answered]
Hi All,

I am trying to setup up the mqtt sensors in the Home Assistant OS. I just can't figure out where in the yaml file I need to update the <`your tesla model`> in the mqtt_sensors.yaml file.

And,

Where can I configure/specify my mqtt port number since it is not the default one as 1883 ?

Any help is appreciated

**Comment by stauffenberg2020** [comment]
@JakobLichterfeld , Then can you please help me with this? 

![image](https://github.com/user-attachments/assets/13be8ace-809d-4817-b490-be13e8a71da3)

**Reply by JakobLichterfeld** [reply]
@longzheng May you assist on this?

**Reply by longzheng** [reply, marked as answer]
@stauffenberg2020 You want to update these values in the first sensor definition

```yaml
- sensor:
    name: Display Name
    object_id: tesla_display_name
    unique_id: teslamate_1_display_name
    availability: &teslamate_availability
      - topic: teslamate/cars/1/healthy
        payload_available: "true"
        payload_not_available: "false"
    device: &teslamate_device_info
      identifiers: [teslamate_car_1]
      configuration_url: https://teslamate.zxxz.io/         # update this with your teslamate URL
      manufacturer: Tesla
      model: Model 3                                        # update this with your car model
      name: Tesla Model 3                                   # update this with your car name
    state_topic: "teslamate/cars/1/display_name"
    icon: mdi:car
```

@JakobLichterfeld yeah I've always found this a bit confusing. I'm not sure how this came to be but I assume the YAML has been written in a way that it can be copy/pasted. I suggest maybe using an inline comment like above rather than the arbitrary text.
