### DISCUSSION TITLE
Db upgrade v15 to v17 - unable to upgrade to tcp, received 409

### DISCUSSION THREAD

**Discussion by sjayanna01** [teslamate-org/teslamate#4363] [General]
My teslamate is setup on portainer, things were working fine with db version 15.

Followed backup instructions, generated bkp file.
Updated docker compose db version.

Facing 'unable to upgrade to tcp, received 409' while executing the below command to restore.
```
docker exec teslamate-db sh -c 'psql -U teslamate teslamate' << .
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
CREATE EXTENSION cube WITH SCHEMA public;
CREATE EXTENSION earthdistance WITH SCHEMA public;
.
```

Docker log shows this:
"FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1)."

Please help, thanks in advance!

**Comment by cwanja** [comment]
Did you delete the database volume? https://docs.teslamate.org/docs/maintenance/upgrading_postgres/

**Comment by BluSpanner** [comment]
Hi,

It looks like you forgot to delete the database volume.
Did you complete step 3?
https://docs.teslamate.org/docs/maintenance/upgrading_postgres

**Comment by sjayanna01** [comment]
I tried, but `docker volume ls` or `docker volume ls -qf dangling=true` doesn't show any volumes related to teslamate or orphaned. How do i find it if its still lurking around somewhere in the background?

**Comment by BluSpanner** [comment]
Hi,

Remove the *_teslamate-db volume, with the following command
docker volume rm "$(basename "$PWD")_teslamate-db"

**Reply by sjayanna01** [reply]
Thanks @BluSpanner , got below response.

docker volume rm "$(basename "$PWD")_teslamate-db"
Error: No such volume: username_teslamate-db

**Reply by sjayanna01** [reply]
This is my docker compose part for teslamate-db

```
  database:
    image: postgres:17
    container_name: teslamate-db
    restart: on-failure:5
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=sdgljadhgweriuowvxvmn
      - POSTGRES_DB=teslamate
    volumes:
      - /volume1/docker/teslamate/teslamate-db:/var/lib/postgresql/data:rw
    networks:
      - caddy_network
```
 
Does manually deleting everything inside teslamate-db folder help?
