### DISCUSSION TITLE
Kinda related: what's the recommended way to get notified that docker containers are unhappy for a homelab setup?

### DISCUSSION THREAD

**Discussion by rubin110** [teslamate-org/teslamate#4782] [Q&A] [answered]
I just hit #4687. Unfortunately I missed that and my Teslamate instance was down since late April until I noticed it just now. I'm running Teslamate on a home server and am not the biggest expert with Docker. Is there a goto method to do health checks on the container, and also get something on the server to notify me if something's down? Thanks.

**Comment by parkr** [comment]
I had issues with Teslamate after a few weeks. My solution was to add an item to my crontab to reboot Teslamate on Sundays at like 4am when it was exceedingly unlikely I'd be in transit anywhere.

**Comment by StarkITA** [comment]
@parkr the issue is that the VERSION of postres changes, and it usually means a major version (es. 1 to 2, rather than 1.1 to 1.2, which can be breaking).

Reboot of crontab might not fix it, afaik the last version jump required me to export db, recreate container with new version, and reimport.

@rubin110 I do not think there is a built-in mechanism, rather than NOT doing auto-updates (watchtower is your enemy here) and reading patchnotes.

The issue is that docker cannot help you. For Docker the container is healthy, and it works correctly since the issue is on the application layer

**Comment by JakobLichterfeld** [comment, marked as answer]
> Is there a goto method to do health checks on the container, and also get something on the server to notify me if something's down? 

TeslaMate does have a health_check endpoint: <your url>/health_check

You can use this in docker-compose.yml, something like this (not tested)

```yml
teslamate:
...
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "if curl -I <put your url here>/health_check 2>&1 | grep -w '200'; then curl --silent -m 5 --retry 2 https://hc-ping.com/<your healthchecks.io endpoint> && exit 0; else exit 1; fi"] # yamllint disable rule:line-length
       interval: 20s # first run after the container is started, and then again interval seconds after each previous check completes
       timeout: 10s # If a single run of the check takes longer than timeout seconds then the check is considered to have failed
       retries: 3 # It takes retries consecutive failures of the health check for the container to be considered unhealthy
       start_period: 40s # provides initialization time for containers that need time to bootstrap
       start_interval: 10s # time between health checks during the start period
 ```

Gold standard is Prometheus, Blackbox Exporter and Alertmanager imo, as I do here: https://github.com/JakobLichterfeld/nix-config/blob/main/homelab/services/teslamate/default.nix


That beeing said: Easies way would be spin up a [uptime-kuma](https://github.com/louislam/uptime-kuma) docker container and set up a status for the TeslaMate health_check endpoint or just use the docker integration.

**Reply by rubin110** [reply]
Thanks. I didn't know uptime kuma could do notifications.

**Comment by maxiride** [comment]
Following @JakobLichterfeld advice I setup the black box exporter to probe Teslamate's health check address.

However, unless I configured something wrong the /health_check endpoint returns 200 OK even if the database is unreachable and teslamate is effectively "not working". Is this behaviour intended?


So far services that have a health check reports OK  when the service itself and all of its dependencies are satisfied so I expected Teslamate to report a KO. Indeed, if I try to open Teslamate dashboard it reports an internal server error.

I did have a look at your Nix [configuration](https://github.com/JakobLichterfeld/nix-config/blob/main/homelab/services/teslamate/default.nix#L75-L83), while I am unfamiliar with Nix seems to me that you are probing the same.


Teslamate dashboard
<img width="408" height="104" alt="image" src="https://github.com/user-attachments/assets/4ed85947-9416-4dc0-b540-78d37e12a0f1" />


Blackbox config
```yml
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
```


Snippet of Prometheus config.

```yaml
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: ["http_2xx"]
    static_configs:
      - targets:
          - "192.168.0.10:4000/health_check" # teslamate health check endpoint
    relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 192.168.0.10:9115 # blackbox own address
```


Probe used tested
```
http://192.168.0.10:9115/probe?target=192.168.0.10:4000/health_check&module=http_2xx&debug=true%22
```


Probe result
```
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 5.951e-06
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.001064255
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 0
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0.000167777
probe_http_duration_seconds{phase="processing"} 0.000651544
probe_http_duration_seconds{phase="resolve"} 5.951e-06
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 4.4174e-05
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 200
# HELP probe_http_uncompressed_body_length Length of uncompressed response body
# TYPE probe_http_uncompressed_body_length gauge
probe_http_uncompressed_body_length 0
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 1.1
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 2.460860959e+09
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 1
```
