### ISSUE TITLE
Database container crashed with an exit code 137 but no OOM error

### ISSUE THREAD

**Issue by pihomeserver** [teslamate-org/teslamate#3131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

An issue popped out few days ago. As soon as the teslamate container starts the DB container crashes with an exit code 137

I tried to clean everything to start with a fresh install and unfortunatly i got the same error after Teslamate container initilises the data structure

I'm able to restore a full backup (using the official doc commands) without a crash

Here is the docker compose file which is very basic and unchanged for a long time
```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    depends_on:
      - database
    ports:
      - 127.0.0.1:4000:4000
    environment:
      - ENCRYPTION_KEY=${TM_ENCRYPTION_KEY}
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - CHECK_ORIGIN=true
      - TZ=${TM_TZ}
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14
#    restart: always
    ports:
      - 54320:5432 
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf    
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  mosquitto-conf:
  mosquitto-data:
```

I'm running the containers on a 16G RAM VPS with 8vCPU

I can't confirm, but it seems to happen after a restart of the containers so maybe a docker issue but i can't find any information on that 
```
Docker version 23.0.1, build a5ee5b1
docker-compose version 1.25.0, build unknown
```

### Expected Behavior

Database container should be up and running

### Steps To Reproduce

Just run the docker compose file

### Relevant log output

```shell
database_1   | 2023-02-23 14:19:18.516 UTC [1] LOG:  starting PostgreSQL 14.7 (Debian 14.7-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
database_1   | 2023-02-23 14:19:18.517 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1   | 2023-02-23 14:19:18.517 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1   | 2023-02-23 14:19:18.535 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1   | 2023-02-23 14:19:18.562 UTC [27] LOG:  database system was interrupted; last known up at 2023-02-23 14:13:44 UTC
database_1   | 2023-02-23 14:19:18.643 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
database_1   | 2023-02-23 14:19:18.653 UTC [27] LOG:  redo starts at 0/18F2770
database_1   | 2023-02-23 14:19:18.653 UTC [27] LOG:  invalid record length at 0/18F27A8: wanted 24, got 0
database_1   | 2023-02-23 14:19:18.653 UTC [27] LOG:  redo done at 0/18F2770 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
database_1   | 2023-02-23 14:19:18.712 UTC [1] LOG:  database system is ready to accept connections
compose.cli.verbose_proxy.proxy_callable: docker wait <- ('d6283826e6df83d2422ee036f6d1eb4c0cd55893d16427b2d93e8767cd87cdc2')
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/d6283826e6df83d2422ee036f6d1eb4c0cd55893d16427b2d93e8767cd87cdc2/wait HTTP/1.1" 200 19
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('d6283826e6df83d2422ee036f6d1eb4c0cd55893d16427b2d93e8767cd87cdc2')
compose.cli.verbose_proxy.proxy_callable: docker wait -> {'StatusCode': 137}
teslamate_database_1 exited with code 137
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/d6283826e6df83d2422ee036f6d1eb4c0cd55893d16427b2d93e8767cd87cdc2/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': '',
 'Args': ['postgres'],
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['postgres'],
            'Domainname': '',
            'Entrypoint': ['docker-entrypoint.sh'],
            'Env': ['POSTGRES_USER=user',
                    'POSTGRES_PASSWORD=password',
...
```

### Screenshots

<img width="813" alt="Capture d’écran 2023-02-23 à 15 22 05" src="https://user-images.githubusercontent.com/3817578/220934847-eee3f746-97e7-4cf3-b62e-0ab7cdc00efa.png">

### Type of installation

Docker

### Version

v1.27.2
