### ISSUE TITLE
most data lost for data to be inserted violate the time constraints

### ISSUE THREAD

**Issue by tl3shi** [teslamate-org/teslamate#3305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After install teslamate successfully, only a few data collected. Most of them are lost. 

I've check the logs and found that may be some time config were not corrected. 

The main logs were attached below.  I am wondering if I mistake some config. 

Here is my docker-compose.yml. 

```yaml
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=xxx
      - DATABASE_USER=teslamate
      - DATABASE_PASS=xxx
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=Asia/Shanghai
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    #image: postgres:15
    image: postgres:13-bullseye
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=xxx
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

### Relevant log output

```shell
teslamate-teslamate-1  | 2023-08-01 21:46:36.042 [error] GenStateMachine :"1" terminating
teslamate-teslamate-1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2023-08-01 13:34:19.013000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate-teslamate-1  |     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:718: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate-teslamate-1  |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate-teslamate-1  |     (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
teslamate-teslamate-1  |     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:713: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate-teslamate-1  |     (stdlib 5.0.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
teslamate-teslamate-1  |     (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
teslamate-teslamate-1  | 2023-08-01 21:46:36.458 [info] Starting logger for '�~_�头�~Z~D车车'
teslamate-teslamate-1  | 2023-08-01 21:46:36.857 car_id=1 [info] Start / :online
teslamate-teslamate-1  | 2023-08-01 21:46:36.866 [error] GenStateMachine :"1" terminating
teslamate-database-1   | 2023-08-01 21:48:43.638 UTC [54] ERROR:  new row for relation "states" violates check constraint "positive_duration"
teslamate-database-1   | 2023-08-01 21:48:43.638 UTC [54] DETAIL:  Failing row contains (9, asleep, 2023-08-01 19:16:39.137466, 2023-08-01 13:36:26.546, 1).
teslamate-database-1   | 2023-08-01 21:48:43.638 UTC [54] STATEMENT:  UPDATE "states" SET "end_date" = $1 WHERE "id" = $2
teslamate-database-1   | 2023-08-01 21:48:44.043 UTC [50] ERROR:  new row for relation "states" violates check constraint "positive_duration"
teslamate-database-1   | 2023-08-01 21:48:44.043 UTC [50] DETAIL:  Failing row contains (9, asleep, 2023-08-01 19:16:39.137466, 2023-08-01 13:36:26.96, 1).
teslamate-database-1   | 2023-08-01 21:48:44.043 UTC [50] STATEMENT:  UPDATE "states" SET "end_date" = $1 WHERE "id" = $2



----------
teslamate-database-1   | 2023-07-31 10:21:20.100 UTC [1375] ERROR:  division by zero

-----------


teslamate-teslamate-1  | 2023-08-01 22:04:46.181 car_id=1 [info] Start / :online
teslamate-teslamate-1  | 2023-08-01 22:04:46.192 [error] GenStateMachine :"1" terminating
teslamate-teslamate-1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2023-08-01 13:52:30.118000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate-teslamate-1  |     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:718: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate-teslamate-1  |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate-teslamate-1  |     (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
teslamate-teslamate-1  |     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:713: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate-teslamate-1  |     (stdlib 5.0.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
teslamate-teslamate-1  |     (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
teslamate-teslamate-1  | 2023-08-01 22:04:46.213 [info] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/xxx -> 429 (15.832 ms)
teslamate-teslamate-1  | 2023-08-01 22:04:46.213 [warning] TeslaApi.Error / "Retry later\n"
teslamate-teslamate-1  | 2023-08-01 22:04:46.213 car_id=1 [error] Error / :unknown
teslamate-teslamate-1  | 2023-08-01 22:05:16.593 car_id=1 [info] Start / :online
teslamate-teslamate-1  | 2023-08-01 22:05:16.599 [error] GenStateMachine :"1" terminating
teslamate-teslamate-1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2023-08-01 13:53:00.528000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate-teslamate-1  |     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:718: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate-teslamate-1  |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate-teslamate-1  |     (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
teslamate-teslamate-1  |     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:713: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate-teslamate-1  |     (stdlib 5.0.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
teslamate-teslamate-1  | waiting for postgres at database:5432
```

### Screenshots

Only some data collected and the location at the main page was two hours ago when I made the screenshot. (However my friends told me that the data are near realtime collected).

![image](https://github.com/adriankumpf/teslamate/assets/491629/34543423-7be5-4636-bd85-bc37701e1043)

### Additional data

no charges info collected, However I have beed changed twice after installation. 

some driver data below:

```csv
8622,1,3,2023-08-01 10:43:44.936,32,3,1,1243.057306,,,,54,,,,,,,,,,,,
8631,1,3,2023-08-01 10:43:51.948,32,2,2,1243.057306,,,,54,,,,,,,,,,,,
8638,1,3,2023-08-01 10:43:56.957,32,2,1,1243.057306,,,,54,,,,,,,,,,,,
8650,1,3,2023-08-01 10:44:09.725,32,2,1,1243.057306,,,,54,,,,,,,,,,,,
8683,1,3,2023-08-01 10:44:57.075,32,0,1,1243.057306,,,,54,,,,,,,,,,,,
8687,1,,2023-08-01 10:45:08.293,,0,1,1242.99706,234.82,211.16,234.82,54,54,,f,f,30.3,27.0,0,22.5,22.5,f,f,f
8688,1,,2023-08-01 10:45:14.094,32,0,1,1243.057306,,,,54,,,,,,,,,,,,
8689,1,,2023-08-01 10:45:18.63,,0,1,1242.99706,234.82,212.03,234.82,54,54,,f,f,30.3,27.0,0,22.5,22.5,f,f,f
8690,1,,2023-08-01 10:45:21.548,,0,1,1242.99706,234.82,212.03,234.82,54,54,,f,f,30.3,27.0,0,22.5,22.5,f,f,f
8691,1,,2023-08-01 10:45:21.548,,0,1,1242.99706,234.82,212.03,234.82,54,54,,f,f,30.3,27.0,0,22.5,22.5,f,f,f
8692,1,,2023-08-01 10:49:10.812,,,0,1242.99706,234.82,212.03,234.82,54,54,,f,f,30.0,27.5,0,22.5,22.5,f,f,f
```

### Type of installation

Docker

### Version

latest
