### ISSUE TITLE
failed to install on Qnap Docker

### ISSUE THREAD

**Issue by madswaord** [teslamate-org/teslamate#3341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i was installed docker on my qnap, for about a year, and it works all good. and tried to delete the docker and reinstall it, the system shows failure. teslamate-teslamate and teslamate-grafana these two containers cannot start up. does anyone know how to solve this issue. thanks.

### Relevant log output

```shell
Background task error for application_custom teslamate: ERROR: for teslamate_grafana_1 Cannot start service grafana: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/run.sh": stat /run.sh: permission denied: unknown Creating teslamate_mosquitto_1 ... done Creating teslamate_teslamate_1 ... error ERROR: for teslamate_teslamate_1 Cannot start service teslamate: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "tini": executable file not found in $PATH: unknown ERROR: for grafana Cannot start service grafana: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/run.sh": stat /run.sh: permission denied: unknown ERROR: for teslamate Cannot start service teslamate: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "tini": executable file not found in $PATH: unknown Encountered errors while bringing up the project.
```

### Screenshots

<img width="1104" alt="截屏2023-09-11 10 48 27" src="https://github.com/adriankumpf/teslamate/assets/86275875/23cbc502-ca67-49f8-89ba-38b9636b683c">

### Type of installation

Docker

### Version

v1.27.3

**Comment by SiNaPsEr0x** [comment]
if you run on qnap I have ts231p3 and I have mod config with arm32 ... your model is?

**Comment by madswaord** [comment]
> if you run on qnap I have ts231p3 and I have mod config with arm32 ... your model is?

my qnap is TS-453Dmini

**Comment by SiNaPsEr0x** [comment]
I'm attaching my file, at most try it if you also have an armv7l

(I also have mods loaded on my teslamate tab)
```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    logging:      
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ENCRYPTION_KEY=YOURDATA
      - DATABASE_USER=teslamate
      - DATABASE_PASS=YOURDATA
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: arm32v7/postgres:15-alpine3.17
    restart: always
    logging:      
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=YOURDATA
      - POSTGRES_DB=teslamate
    ports:
      - 5432:5432
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    logging:      
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DATABASE_USER=YOURDATA
      - DATABASE_PASS=YOURDATA
      - DATABASE_NAME=YOURDATA
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
      - /share/Container/container-station-data/application/teslamate/Teslamate-CustomGrafanaDashboards/customdashboards.yml:/etc/grafana/provisioning/dashboards/customdashboards.yml
      - /share/Container/container-station-data/application/teslamate/Teslamate-CustomGrafanaDashboards/dashboards:/TeslamateCustomDashboards

  mosquitto:
    image: seblucas/alpine-mosquitto:latest
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
#    command: -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```
