### ISSUE TITLE
Cannot deploy onto synology - db error

### ISSUE THREAD

**Issue by sedetweiler** [teslamate-org/teslamate#3449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am using the Marius guide for installation on my 920+ but I always hit this same error since Jan, so now that dev seems like it is alive again I thought I would try again, but the error is the same.

### Expected Behavior

Install stack would deploy in docker

### Steps To Reproduce

create yaml file
create empty directories
set security permissions to write enable and include subs
create yaml in portainer
deploy stack

### Relevant log output

```shell
failed to deploy a stack: Volume "teslamate_teslamate-db" Creating Volume "teslamate_teslamate-db" Created Volume "teslamate_teslamate-grafana-data" Creating Volume "teslamate_teslamate-grafana-data" Created Volume "teslamate_mosquitto-conf" Creating Volume "teslamate_mosquitto-conf" Created Volume "teslamate_mosquitto-data" Creating Volume "teslamate_mosquitto-data" Created Container teslamate-database-1 Creating Container teslamate-grafana-1 Creating Container teslamate-mosquitto-1 Creating Container teslamate-teslamate-1 Creating Container teslamate-teslamate-1 Created Container teslamate-grafana-1 Created Container teslamate-database-1 Created Container teslamate-mosquitto-1 Created Container teslamate-mosquitto-1 Starting Container teslamate-grafana-1 Starting Container teslamate-database-1 Starting Container teslamate-teslamate-1 Starting Container teslamate-mosquitto-1 Started Container teslamate-grafana-1 Started Container teslamate-database-1 Started Error response from daemon: Bind mount failed: '/data/compose/1/import' does not exists
```

### Type of installation

Docker

### Version

current pull

**Comment by JakobLichterfeld** [comment]
Please make sure to follow https://docs.teslamate.org/docs/installation/docker. 
Please provide your docker-compose.yml file without credentials.

**Comment by sedetweiler** [comment]
This is what I am using for my yaml file ### has been put in place rather than creds.
I am hoping there is something obvious for you here, as I am at a complete loss on this.

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY= ###
      - DATABASE_USER=teslamate
      - DATABASE_PASS= ###
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD= ###
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS= ###
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```
