### ISSUE TITLE
New dashboards (v1.27.4 onward) 404 in Grafana

### ISSUE THREAD

**Issue by RickyRomero** [teslamate-org/teslamate#3494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the main TeslaMate app page, there's a menu at the top linking to various dashboards. Some are new as of v1.27.4 onward:

- Battery Health
- Battery Health - LFP
- Charging Stats - LFP
- Overview - LFP

These links lead to an empty Grafana page on my installation which looks like this.

![Screen Shot 2023-11-25 at 20 47 13 - Safari@2x](https://github.com/teslamate-org/teslamate/assets/233891/c1c53238-e53c-439d-9a87-8b5fbad0d469)

All other dashboards work as expected.

### Expected Behavior

I expect one of these behaviors:

- TeslaMate should not link to dashboards which cannot be found, or
- Grafana should display the dashboard containing the requested information.

### Steps To Reproduce

1. Open your TeslaMate installation.
2. In the top nav bar, choose "Dashboards."
3. Choose one of the four dashboards listed previously.

### Relevant log output

```shell
teslamate-grafana-1    | logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2023-11-25T20:52:02.53-0800 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=10.0.5.2 time_ms=0 duration=853.065µs size=0 referer= traceID=00000000000000000000000000000000
teslamate-grafana-1    | logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2023-11-25T20:52:02.63-0800 lvl=eror msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.5.2 traceID=00000000000000000000000000000000
teslamate-grafana-1    | logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2023-11-25T20:52:02.63-0800 lvl=info msg="Request Completed" method=GET path=/api/dashboards/uid/jchmRiqUfXgTM status=404 remote_addr=10.0.5.2 time_ms=0 duration=255.19µs size=78 referer=http://charts.lan/d/jchmRiqUfXgTM traceID=00000000000000000000000000000000
```

### Type of installation

Docker

### Version

v1.29.0-dev

**Comment by swiffer** [comment]
Dashboards are not retrieved from running Grafana instance but based on list of available Dashboards in the latest version. You would need to import latest Dashboards into Grafana. Have you imported them manually or are you using the grafana docker container from this repo? has it been updated?

**Comment by swiffer** [comment]
#3496 
#3499 

could be related (volumes created by older versions of the grafana image might need to be dropped and recreated - can someone test please?)

**Comment by RickyRomero** [comment]
My setup persists Grafana data through the host's filesystem, in `./data/grafana`. I archived the `./data/grafana` directory, recreated the directory, then ran:
`sudo docker-compose down; sudo docker-compose pull; sudo docker-compose up -d --build --force-recreate`

There appears to be no change. All the previous dashboards work, but none of the new ones appear to function. This is my `docker-compose.yaml` entry for Grafana:

```yaml
  grafana:
    image: 'teslamate/grafana'
    restart: 'unless-stopped'
    env_file: './.env'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxied-services'
      - 'traefik.http.routers.grafana.rule=Host(`charts.lan`)'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
      - 'traefik.http.routers.grafana.entrypoints=web'
    volumes:
      - './data/grafana:/var/lib/grafana'
      - './healthcheck:/healthcheck:ro'
    networks:
      - 'proxied-services'
      - 'teslamate'
    ports:
      - '3000:3000/tcp'
    healthcheck:
      test: ['CMD', 'sh', '/healthcheck/grafana.sh']
      interval: 120s
      timeout: 10s
      retries: 5
      start_period: 300s
```

How do I manually import the new dashboards?
