### ISSUE TITLE
Tesla version 2023.44.30.2 broke Teslamate

### ISSUE THREAD

**Issue by sfintel** [teslamate-org/teslamate#3581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading to Tesla software 2023.44.30.2, Teslamate is no longer able to communicate with either of my cars. I logged out and back into the Auth for Tesla app and generated fresh tokens. I then logged out and back in to Teslamate using the new tokens.

### Expected Behavior

Able to

### Relevant log output

```shell
teslamate_1  | 2023-12-22 18:13:32.980 [info] Starting logger for 'Berta'
teslamate_1  | 2023-12-22 18:13:32.985 [info] Starting logger for 'Greyson'
teslamate_1  | 2023-12-22 18:13:33.094 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492931853273797 -> 429 (98.243 ms)
teslamate_1  | 2023-12-22 18:13:33.094 [warning] TeslaApi.Error / "Retry later\n"
teslamate_1  | 2023-12-22 18:13:33.094 car_id=1 [error] Error / :unknown
teslamate_1  | 2023-12-22 18:13:33.121 car_id=2 [info] Start / :asleep
teslamate_1  | 2023-12-22 18:13:43.228 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1493078324478777 -> 429 (100.780 ms)
teslamate_1  | 2023-12-22 18:13:43.228 [warning] TeslaApi.Error / "Retry later\n"
teslamate_1  | 2023-12-22 18:13:43.228 car_id=2 [error] Error / :unknown
```

### Type of installation

Docker

### Version

v1.27.3

**Comment by cwanja** [comment]
What happens if you upgrade to the latest version of TeslaMate?

**Comment by sfintel** [comment]
I think 1.27.3 is the most current version. Just in case, I just did a new pull, and nothing changed.

**Comment by cwanja** [comment]
1.28.X is the latest TeslaMate. Based upon the errors, it seems like a Tesla API endpoint failure. Does the app work?

**Comment by sfintel** [comment]
I never got notification of 1.28.x. When I pull the container (sudo docker-compose pull), I'm up to date with 1.27.3. My docker-compose.yml file says:

`image: teslamate/teslamate:latest`

What am I missing?

**Comment by cwanja** [comment]
Can your container connect to the internet?

**Comment by sfintel** [comment]
I've never had a problem with that in the past. I get email notifications for new releases, but never saw one for 1.28.x

**Comment by cwanja** [comment]
Not sure what to tell you about notification. Double check you are subscribed to releases. As for your container, check its connection to the internet. Or post your entire YML file, redacting passwords.

**Comment by sfintel** [comment]
I just verified that I'm subscribed to release notifications. Here's my docker-compose.yml  file:

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=****************
      - DATABASE_USER=***********
      - DATABASE_PASS=***********
      - DATABASE_NAME=***********
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=*********
      - POSTGRES_PASSWORD=**********
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=************
      - DATABASE_PASS=************
      - DATABASE_NAME=**********
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

```
