### ISSUE TITLE
TZ environment variable name confusion

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3678]
>I don't know why or how your reply explains my confusion. The fact is using "TZ=" was not enough but instead a line with "TM_TZ=" works yet is not in the documentation written as "TM_TZ=". Am I just missing something that should be "obvious"?

_Originally posted by @TSJasonH in https://github.com/teslamate-org/teslamate/issues/3651#issuecomment-1946031327_

**Comment by JakobLichterfeld** [comment]
@TSJasonH please share your docker-compose file (without your secrets). The name of the environment variable is `TZ`without any TM_

**Comment by TSJasonH** [comment]
sure...

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=*redacted*
      - DATABASE_USER=teslamate
      - DATABASE_PASS=*redacted*
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ="America/Indiana/Indianapolis"      
      - TM_TZ="America/Indiana/Indianapolis"   
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=*redacted*
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data  

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=*redacted*
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

**Comment by brianmay** [comment]
Random thought: I would like to be able to see the current timezone that is in use when the car is not charging. Maybe something to print the last refresh date/time in the live view or something like that would be a good idea.

**Comment by maxhac03** [comment]
Been using TM_TZ in the .env file since 2019. Both TeslaMate and Grafana reported the correct time since.


Here the instruction for the .env file does mention TM_TZ:
https://docs.teslamate.org/docs/guides/traefik

All i did was change the zone and kept the same variable to fix the issue.

![Screenshot_20240215-180146](https://github.com/teslamate-org/teslamate/assets/64552097/ad6d8c78-ac15-4f5c-bf4d-ef58da3d8fd5)
![screenshot 21](https://github.com/teslamate-org/teslamate/assets/64552097/f95e4711-9dca-4521-9d96-53341f57fa05)
![screenshot 22](https://github.com/teslamate-org/teslamate/assets/64552097/cf17ca4b-67ef-44e6-9210-5724e40100ee)

**Comment by brianmay** [comment]
Note the referenced instructions set `TZ=${TM_TZ}` in the docker-compose file.

So doing in this way makes sense. TeslaMate is reading the `TZ` value, which is set from the `TM_TZ` value.

But there is nothing in TeslaMate - that I am aware of - that reads the `TM_TZ` environment variable directly.

The docker-compose file quoted above does not have the  `TZ=${TM_TZ}` line.

**Comment by touchton** [comment]
Just to add another data point, my .yml file has the following:
TZ=America/Chicago

Nothing about TM_TZ in the file at all.  I'm not having a problem; time is being displayed correctly in both the Teslamate page and Grafana pages.

I don't know if this information helps or hurts...  I'm running the container locally in a Photon VM on an ESX host.

**Comment by cwanja** [comment]
For what it is worth, a user on TMC changed the variable **from** `TZ` to `TM_TZ` and their internal server error on TeslaMate webpage during charging went away. 
https://teslamotorsclub.com/tmc/threads/teslamate-megathread.191537/page-164#post-8088719

**Comment by brianmay** [comment]
That does make sense. If `TZ` is wrong, then TeslaMate will see it and this will create the error. If `TM_TZ` is wrong, it doesn't matter, TeslaMate won't look at that and continue working using whatever the system default timezone is.

**Comment by JakobLichterfeld** [comment]
> sure...
> 
> ```
> version: "3"
> 
> services:
>   teslamate:
>     image: teslamate/teslamate:latest
>     restart: always
>     environment:
>       - ENCRYPTION_KEY=*redacted*
>       - DATABASE_USER=teslamate
>       - DATABASE_PASS=*redacted*
>       - DATABASE_NAME=teslamate
>       - DATABASE_HOST=database
>       - MQTT_HOST=mosquitto
>       - TZ="America/Indiana/Indianapolis"      
>       - TM_TZ="America/Indiana/Indianapolis"   
>     ports:
>       - 4000:4000
>     volumes:
>       - ./import:/opt/app/import
>     cap_drop:
>       - all
> 
>   database:
>     image: postgres:13
>     restart: always
>     environment:
>       - POSTGRES_USER=teslamate
>       - POSTGRES_PASSWORD=*redacted*
>       - POSTGRES_DB=teslamate
>     volumes:
>       - teslamate-db:/var/lib/postgresql/data  
> 
>   grafana:
>     image: teslamate/grafana:latest
>     restart: always
>     environment:
>       - DATABASE_USER=teslamate
>       - DATABASE_PASS=*redacted*
>       - DATABASE_NAME=teslamate
>       - DATABASE_HOST=database
>     ports:
>       - 3000:3000
>     volumes:
>       - teslamate-grafana-data:/var/lib/grafana
> 
>   mosquitto:
>     image: eclipse-mosquitto:2
>     restart: always
>     command: mosquitto -c /mosquitto-no-auth.conf
>     # ports:
>     #   - 1883:1883
>     volumes:
>       - mosquitto-conf:/mosquitto/config
>       - mosquitto-data:/mosquitto/data
> 
> volumes:
>   teslamate-db:
>   teslamate-grafana-data:
>   mosquitto-conf:
>   mosquitto-data:
> ```

Even if it is not related to the issue, here, you need to update your postgres database container, please do a backup and follow https://docs.teslamate.org/docs/maintenance/upgrading_postgres

**Comment by JakobLichterfeld** [comment]
> - TZ="America/Indiana/Indianapolis"

The issue are the `"`. Please remove the unneeded TM_TZ and replace with `- TZ=America/Indiana/Indianapolis`

**Comment by TSJasonH** [comment]
Looks good. Quotes...who knew :-/

Also thanks for the db upgrade tip. Completed the upgrade to pg 15 smoothly with the provided instructions.

**Comment by Olyts** [comment]
The issue was fixed when I replaced to TZ by TM_TZ. As mentioned by @cwanja Now the web page is coming up while charging (no more 500 server error), but the time is 5.5 hours off. Although my TZ is set to America/Toronto? Grafana info is spot on about drive time and charge time, it is not just not showing up right on the Teslamate homepage.(+5,5 hours), As an example, at an expected local 8h15 finish time, it was showing 13h45. I’m not worried much, just want to report here.

**Comment by brianmay** [comment]
I think it might help if the time displayed the timezone offset, that would help verify that the timezone is correct.

**Comment by ampersandru** [comment]
was getting internal server errors, tried TM_TZ and it still didnt fix it.
 
Rolled back to teslamate/teslamate:1.28.2 and its working fine again with just the TZ env

**Comment by JakobLichterfeld** [comment]
> was getting internal server errors,

If you ask for help, please share your docker-compose (without credentials)

**Comment by JakobLichterfeld** [comment]
Total agree. Not only valid for TZ

**Comment by ampersandru** [comment]
> > was getting internal server errors,
> 
> If you ask for help, please share your docker-compose (without credentials)

This is the docker-compose i used a couple years ago initially, but have been using watchtower to update the stack

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_angeles
      - ENCRYPTION_KEY=ABCDefg
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=192.168.29.234
      - MQTT_PORT=1883
    ports:
      - 4000:4000
    volumes:
      - /volume2/docker/teslamate/import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14
    restart: always
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/Los_angeles    
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/volume2/docker/teslamate/postgresql

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/Los_angeles    
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/volume2/docker/grafana

volumes:
  teslamate-db:
  teslamate-grafana-data:


```
