### ISSUE TITLE
Programatic way to cancel sleep attempt

### ISSUE THREAD

**Issue by pushpak1990** [teslamate-org/teslamate#3701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My routine in the morning means that the EV is trying to sleep while I leave. I open the website and ask it to cancel sleep attempt. Is there a way for me programmatically do this from Home Assistant using Garage door opening as a trigger?

Something like a MQTT command?

### Relevant log output

```shell
NA
```

### Type of installation

Docker

### Version

v1.28.3

**Comment by brianmay** [comment]
I *think* if you can do a HTTP PUT request to `/api/car/:id/logging/resume` it should wake up TeslaMate. Replace `:id` with the id TeslaMate has given your car.

It should be possible to configure Home Assistant to do this.

Ideally this needs to be documented somewhere, I don't see any of this in the docs (I might have missed it...).

**Comment by djpalmis** [comment]
May I ask you just "why"?
Also: why don't you use sentry mode?

**Comment by cwanja** [comment]
> May I ask you just "why"? Also: why don't you use sentry mode?

Not the original poster, but my car is garaged so no need for Sentry mode. if I open my car for something (e.g. move a car seat) and then five or ten minutes later leave, the car is attempting to fall asleep in this window. I can see a need.

**Comment by pushpak1990** [comment]
> May I ask you just "why"?
2 Reasons:
- Exactly the same as mentioned here: https://github.com/teslamate-org/teslamate/issues/3701#issuecomment-1971845774
- I have a Garage door opener that can disable the Remote (a security feature if you will). So I need an automation to wake up teslamate to wake up as soon as I enter the garage. So I can use automation and look for the pattern of 
  - Door Open
  - User Present
  - Door Close
  to disable this security feature so I can open the garage from inside the car
> Also: why don't you use sentry mode?
No need for sentry mode inside the garage

**Comment by pushpak1990** [comment]
Quick Feedback here. The command mentioned [here](https://github.com/teslamate-org/teslamate/issues/3701#issuecomment-1970159545) worked well. Thank you very much. Are there any other commands similar to this? Where can I find them?

**Comment by brianmay** [comment]
There is a suspect logging command also. That is all.

https://github.com/teslamate-org/teslamate/blob/71f5fd4d2a09ffd349d48587a2a18a3ab87cbb9a/lib/teslamate_web/router.ex#L53-L54

**Comment by Dhtjf** [comment]
@pushpak1990 could you provide an example of how you accomplished the HTTP PUT action in a home assistant action?
I'd like to utilize this paired with the trigger of my phone connecting to the car and am struggling a bit on the action.

**Comment by pushpak1990** [comment]
Sure, 

# Script File

I saved this as `/config/wake_teslamate.sh`
Make sure that you set execution access to this file (`chmod +x /config/wake_teslamate.sh`)

```shell
# Wake Up Nirma
curl -X PUT https://teslamate.xxx/api/car/1/logging/resume

# Wake Up Ujala
curl -X PUT https://teslamate.xxx/api/car/2/logging/resume
```

# Cofiguration file

This is to tell Home Assistant about the shell script

```yaml
shell_command:
  teslamate_wake: /config/wake_teslamate.sh
```

# Automation

```yaml
- id: '1709425312585'
  alias: Garage Door Opened
  description: ''
  trigger:
  - platform: state
    entity_id:
    - cover.garage_door
    from: closed
    to: open
  condition: []
  action:
  - service: shell_command.teslamate_wake
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: script.insecure_garage
    metadata: {}
    data: {}
  - if:
    - condition: state
      entity_id: binary_sensor.home_mode_is_away
      state: 'on'
    then:
    - service: notify.group_status_change_telegram
      metadata: {}
      data:
        title: Garage Door Open
        message: Garage Door Open. Nobody at home. Will auto close in 30 seconds
    - delay:
        hours: 0
        minutes: 0
        seconds: 30
        milliseconds: 0
    - service: cover.close_cover
      metadata: {}
      data: {}
      target:
        entity_id: cover.garage_door
  mode: single
```

**Comment by Dhtjf** [comment]
Thank you @pushpak1990 very much!
Slightly different method for my HA OS install on a VM, included for clarity for anyone else.

Script:
```
alias: Wake TeslaMate
sequence:
  - service: rest_command.wake_teslamate
    data: {}
mode: single
icon: mdi:car-electric
```
Config:
replacing TESLAMATESERVER and PORT with the appropriate address and port for teslamate, reachable from HA.
```
rest_command:
  wake_teslamate:
    url: "http://TESLAMATESERVER:PORT/api/car/1/logging/resume"
    method: put
```

Then just call "service: script.wake_teslamate" to wake teslamate logging.
