### ISSUE TITLE
Upgrading via docker-compose from v1.28.3 to v1.28.4 results in unusable system with "404 page not found" error

### ISSUE THREAD

**Issue by SemoTech** [teslamate-org/teslamate#3754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to upgrade via docker-compose from v1.28.3 to v1.28.4 and now getting "404 page not found" when trying to access Teslamate.  Grafana is still accessible and works tho!

Rebooting does NOT fix the problem!

**SOLUTION:  Docker v19 needing to be upgraded to V26 BEFORE upgrading from Teslamate v1.28.3 to v1.28.4 (may work in V20 too)**

### Expected Behavior

Expected update to be successful and to see the Teslamate login window

### Steps To Reproduce

Issued the following commands to performed the update, and no errors occurred:

`docker-compose pull && docker-compose up -d`

Results:

```
Pulling teslamate ... done
Pulling database ... done
Pulling grafana ... done
Pulling mosquitto ... done
Pulling proxy ... done
root_proxy_1 is up-to-date
Recreating root_grafana_1 ... 
Recreating root_grafana_1  ... done
Recreating root_database_1 ... done
Recreating root_teslamate_1 ... done
[root@teslamate ~]# 
```

### Relevant log output

```shell
[root@teslamate ~]# docker-compose logs teslamate
Attaching to root_teslamate_1
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Failed to create thread: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
[root@teslamate ~]# 



[root@teslamate ~]# docker-compose logs proxy
proxy_1      | time="2024-03-20T19:38:36Z" level=info msg="Configuration loaded from flags."
proxy_1      | time="2024-03-20T19:43:45Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:43:45Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:43:46Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:43:47Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:43:48Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205 providerName=docker
proxy_1      | time="2024-03-20T19:43:50Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205 providerName=docker
proxy_1      | time="2024-03-20T19:43:54Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:44:01Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:44:15Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:44:41Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:45:33Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:46:33Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:47:34Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:48:34Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:49:35Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205 providerName=docker
proxy_1      | time="2024-03-20T19:50:36Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:51:36Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
proxy_1      | time="2024-03-20T19:52:37Z" level=error msg="service \"teslamate-root\" error: unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-20a8a3399c90d537a0be4a539631400ce9f97e1be15c3b51b40296dab1c02205
[root@teslamate ~]#
```

### Type of installation

Docker

### Version

v1.28.4

**Comment by cwanja** [comment]
Several had updated to 1.28.4 without issues, so I tend to believe this is not an “issue”, but will leave it for the moment. 

What is your storage like on the host device? What does your YML file look like? What version of docker are you running?

**Comment by SemoTech** [comment]
> Several had updated to 1.28.4 without issues, so I tend to believe this is not an “issue”, but will leave it for the moment.
> 
> What is your storage like on the host device? What does your YML file look like? What version of docker are you running?

This is a Vultr VM running CentOS 7 with 25GB Storage and Docker version 19.03.7, build 7141c199a2

Here is the rest of the info (restored back to v1.28.3 using a backup image, BEFORE the update to v1.28.4 which consistently fails):

```
[root@teslamate ~]# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                      NAMES
1c43fa5a5fdf        teslamate/teslamate:latest   "tini -- /bin/sh /en‚Ä¶"   6 weeks ago         Up About an hour    4000/tcp                                   root_teslamate_1
05db1ee60217        teslamate/grafana:latest     "/run.sh"                6 weeks ago         Up About an hour    3000/tcp                                   root_grafana_1
6147aa002265        postgres:12                  "docker-entrypoint.s‚Ä¶"   6 weeks ago         Up About an hour    5432/tcp                                   root_database_1
ed9c932e0fb1        eclipse-mosquitto:1.6        "/docker-entrypoint.‚Ä¶"   9 months ago        Up About an hour    127.0.0.1:1883->1883/tcp                   root_mosquitto_1
b92bd163fb82        traefik:v2.1                 "/entrypoint.sh --gl‚Ä¶"   3 years ago         Up About an hour    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   root_proxy_1
[root@teslamate ~]# 
[root@teslamate ~]# 
[root@teslamate ~]# docker inspect 1c43fa5a5fdf | grep com.docker.compose
                "com.docker.compose.config-hash": "15736609df597e3fc789ffebb873510e81ff647ec4ac41b4a36880fec729d306",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "root",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/root",
                "com.docker.compose.service": "teslamate",
                "com.docker.compose.version": "1.25.4",
[root@teslamate ~]# 
[root@teslamate ~]# cat docker-compose.yml
version: '3'

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY=${TM_ENCRYPTION_KEY} 
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - CHECK_ORIGIN=true
      - TZ={$TM_TZ}
    volumes:
      - ./import:/opt/app/import
    labels:
      - "traefik.enable=true"
      - "traefik.port=4000"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/.htpasswd"
      - "traefik.http.routers.teslamate-insecure.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate-insecure.middlewares=redirect"
      - "traefik.http.routers.teslamate-ws.rule=Host(`${FQDN_TM}`) && Path(`/live/websocket`)"
      - "traefik.http.routers.teslamate-ws.entrypoints=websecure"
      - "traefik.http.routers.teslamate-ws.tls"
      - "traefik.http.routers.teslamate.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate.middlewares=auth"
      - "traefik.http.routers.teslamate.entrypoints=websecure"
      - "traefik.http.routers.teslamate.tls.certresolver=tmhttpchallenge"
    cap_drop:
      - all

  database:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_FROM_NAME=${GF_SMTPNAME}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTPSENDER}
      - GF_SMTP_HOST=${GF_SMTPHOST}                      
      - GF_SMTP_USER=${GF_SMTPUSER}                   
      - GF_SMTP_PASSWORD=${GF_SMTPPASS}
      - GF_SMTP_SKIP_VERIFY=false
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=3000'
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana-insecure.rule=Host(`${FQDN_GRAFANA}`)"
      - "traefik.http.routers.grafana-insecure.middlewares=redirect"
      - "traefik.http.routers.grafana.rule=Host(`${FQDN_GRAFANA}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=tmhttpchallenge"

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 127.0.0.1:1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  proxy:
    image: traefik:v2.1
    restart: always
    command:
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.tmhttpchallenge.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.tmhttpchallenge.acme.storage=/etc/acme/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.htpasswd:/auth/.htpasswd
      - ./acme/:/etc/acme/
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:

[root@teslamate ~]# 
```
