### ISSUE TITLE
v1.28.4 fails to start with Permission denied error

### ISSUE THREAD

**Issue by rpearson-catdevnull** [teslamate-org/teslamate#3769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading to v1.28.4 container fails to start with error:

`
/entrypoint.sh: 14: bin/teslamate: Permission denied
`

My docker-compose file for teslamate is below:

```
  teslamate:
    image: teslamate/teslamate:1.28.4
    restart: always
    container_name: teslamate
    environment:
      - ENCRYPTION_KEY=XXXXX
      - DATABASE_USER=teslamate
      - DATABASE_PASS=XXXXX
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    user: "1003:1007"
    volumes:
      - /opt/docker/volumes/teslamate/import:/opt/app/import
    cap_drop:
      - all
```

Downgrading to v1.28.3 brought teslamate back to life again. I'm assuming it might be something to do with the fact I run it in its own user/group `user: "1003:1007"`?

### Expected Behavior

I'd expect teslamate to start :joy:

### Steps To Reproduce

- Upgrade image to v1.28.4
- Observe

### Relevant log output

```shell
/entrypoint.sh: 14: bin/teslamate: Permission denied
```

### Type of installation

Docker

### Version

v1.28.4
