### ISSUE TITLE
Statistics page "Starting at" data / column incorrect

### ISSUE THREAD

**Issue by towster** [teslamate-org/teslamate#3857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using drives as an example but goes for charges as well. I took screenshot of time range "last 2 days" at 8:20pm CDT.
<img width="760" alt="Screenshot 2024-04-17 at 8 20 20 PM" src="https://github.com/teslamate-org/teslamate/assets/1965956/be930d11-1059-4776-8a9e-b346bc833810">

First off timezone. Every time I goto statistics page it resets the timezone to Berlin. My browser and My profile have it set to Chicago. 

Next we have when a day starts. Current time of screenshot is 8:20pm. I have selected day view and last two days. Shows me 3 days.  The first day is the 18th (tomorrow!) which apparently starts at 7pm today (the 17th). It shows I have driven 3 places in the past 1 hour and 20 minutes. The lefthand column in the screenshot of the dates/times are my drives for the last 2 days.  My most recent drive was 4/17 @ 6:07 (for 6 minutes) or 2 hours and 7 minutes ago. None of these drives are after the cutoff time shown.

### Expected Behavior

timezone should be set properly when going to page

the time that a day should start should be midnight. Count of number of drives should match the number of drives for that day  as shown in drives page.

### Steps To Reproduce

Goto statistics page
change time period to days
set time range to last 2 days

### Relevant log output

```shell
teslamate-1  | 2024-04-17 20:34:31.270 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9178.959 ms)
teslamate-1  | 2024-04-17 20:34:31.271 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:34:31.271 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:36:08.682 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9143.538 ms)
teslamate-1  | 2024-04-17 20:36:08.682 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:36:08.682 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:36:37.808 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9124.815 ms)
teslamate-1  | 2024-04-17 20:36:37.808 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:36:37.809 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:37:06.946 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9136.254 ms)
teslamate-1  | 2024-04-17 20:37:06.946 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:37:06.946 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:38:58.978 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9130.891 ms)
teslamate-1  | 2024-04-17 20:38:58.979 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:38:58.979 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:39:28.125 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9145.764 ms)
teslamate-1  | 2024-04-17 20:39:28.125 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:39:28.125 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:39:57.273 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9146.948 ms)
teslamate-1  | 2024-04-17 20:39:57.274 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:39:57.274 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:40:26.409 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9134.388 ms)
teslamate-1  | 2024-04-17 20:40:26.409 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:40:26.409 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:42:02.156 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9159.892 ms)
teslamate-1  | 2024-04-17 20:42:02.156 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:42:02.157 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:42:31.301 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9143.539 ms)
teslamate-1  | 2024-04-17 20:42:31.301 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:42:31.301 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:43:00.427 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9124.103 ms)
teslamate-1  | 2024-04-17 20:43:00.427 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:43:00.427 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:43:12.974 [info] GET /
teslamate-1  | 2024-04-17 20:43:12.978 [info] Sent 200 in 4ms
teslamate-1  | 2024-04-17 20:43:17.813 [info] GET /settings
teslamate-1  | 2024-04-17 20:43:17.822 [info] Sent 200 in 9ms
teslamate-1  | 2024-04-17 20:43:29.601 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9172.466 ms)
teslamate-1  | 2024-04-17 20:43:29.601 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:43:29.601 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:43:58.720 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9117.199 ms)
teslamate-1  | 2024-04-17 20:43:58.720 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:43:58.720 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:44:27.867 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9145.749 ms)
teslamate-1  | 2024-04-17 20:44:27.867 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:44:27.867 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:44:57.021 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9152.151 ms)
teslamate-1  | 2024-04-17 20:44:57.021 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:44:57.021 car_id=1 [error] Error / :unknown
teslamate-1  | 2024-04-17 20:44:59.346 [info] GET /
teslamate-1  | 2024-04-17 20:44:59.350 [info] Sent 200 in 4ms
teslamate-1  | 2024-04-17 20:45:26.163 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/3744882384725593848/vehicle_data -> 408 (9141.873 ms)
teslamate-1  | 2024-04-17 20:45:26.163 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate-1  | 2024-04-17 20:45:26.163 car_id=1 [error] Error / :unknown
```

### Type of installation

Docker

### Version

1.28.5

**Comment by DrMichael** [comment]
> ### What happened?
> First off timezone. Every time I goto statistics page it resets the timezone to Berlin. My browser and My profile have it set to Chicago.
Interesting. Can you please look, which timezone the database has?
`docker compose exec database psql -U teslamate -d teslamate
`Then
`SELECT current_setting('TIMEZONE');`

(BTW, the logs are not helping, they just say, that your teslamate could not connect to the tesla servers. That might happen.)

**Comment by towster** [comment]
Yeah i know the logs didnt help but it was a required field.. thx for confirming at least that it is normal for tesla to have server down.. ;)

```
WARN[0000] /root/docks/teslamate/docker-compose.yml: `version` is obsolete 
psql (15.6 (Debian 15.6-1.pgdg120+2))
Type "help" for help.

teslamate=# SELECT current_setting('TIMEZONE');
 current_setting 
-----------------
 Etc/UTC
(1 row)

teslamate=#
```

Hasnt been asked for but.. I only added the TZ setting to the other containers after i saw it was having this issue.. it didnt change anything..

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=___NOT_MY_PASS___ #replace with a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS=___NOT_MY_PASS___ #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=America/Chicago
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=___NOT_MY_PASS___ #insert your secure database password!
      - POSTGRES_DB=teslamate
      - TZ=America/Chicago
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=___NOT_MY_PASS___ #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - TZ=America/Chicago
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```
