### ISSUE TITLE
Unable to restore a teslamate database backup using docker compose (v2) under Portainer

### ISSUE THREAD

**Issue by SemoTech** [teslamate-org/teslamate#3968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Followed the tutorial in the official teslamate manual for Backup & Restore [HERE](https://docs.teslamate.org/docs/maintenance/backup_restore) and managed to backup the DB from a source cloud host, but unable to restore it to the target host. Both host servers use the same Docker and Docker Compose V2 CLI versions.  

- On the source host the [advanced install with traefik](https://docs.teslamate.org/docs/guides/traefik) configuration was used, but with 2 FQDN's
- On the target host I am using Portainer and Caddy in a separate stack/container, instead of traefik and a single FQDN. The configuration is below...

### Expected Behavior

DB Import process should work

### Steps To Reproduce

I successfully exported/backed-up the database on the source host using the command:
`sudo docker compose exec -T database pg_dump -U teslamate teslamate > ./teslamate.bck`

However, I am unable to restore the database backup file copied onto the target host using the command:
`sudo docker compose exec -T database psql -U teslamate -d teslamate < ./teslamate.bck`

Docker compose puts out an error stating:
`no configuration file provided: not found`

Just to be sure I was working with the correct database, i used the actual container names and also tried:
`sudo docker compose exec -T teslamate-postgres psql -U teslamate -d teslamate < ./teslamate.bck`

But got the same error/result:
`no configuration file provided: not found`

Lastly, I tried this command and while no error occurred, no data was imported either:
`sudo docker exec teslamate-postgres psql -U teslamate -d teslamate < ./teslamate.bck`

### Relevant log output

```shell
no relevant logs
```

### Screenshots
![image](https://github.com/teslamate-org/teslamate/assets/1452100/a05b70d6-d97d-4e9a-8ca6-ce78e406dfc7)

### Additional data

Docker is version  v26.1.4
docker compose is version v2.27.1

Here is the target host Stack configuration (docker-compose.yml)"
```
version: "3"

services:
  teslamate:
    container_name: teslamate
    image: teslamate/teslamate:latest
    restart: unless-stopped
    environment:
      - ENCRYPTION_KEY=${TM_ENCRYPTION_KEY}
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=teslamate-postgres
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - CHECK_ORIGIN=true
      - NTP_SERVERS=${TM_NTP}
      - TZ=${TM_TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  
    networks:
      tm-net:
      caddy-net:      
    volumes:
      - /root/docker/teslamate/import:/opt/app/import
    cap_drop:
      - all

  postgres:
    container_name: teslamate-postgres
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}   
    networks:
      tm-net:
    volumes:
      - /root/docker/teslamate/teslamate-db:/var/lib/postgresql/data

  grafana:
    container_name: teslamate-grafana
    image: teslamate/grafana:latest
    restart: unless-stopped
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_DOMAIN=${FQDN_TM}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_FROM_NAME=${GF_SMTPNAME}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTPSENDER}
      - GF_SMTP_HOST=${GF_SMTPHOST}                      
      - GF_SMTP_USER=${GF_SMTPUSER}                   
      - GF_SMTP_PASSWORD=${GF_SMTPPASS}
      - GF_SMTP_SKIP_VERIFY=false
    user: "root:root"
    networks:
      tm-net:
      caddy-net:     
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /root/docker/teslamate/teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    container_name: teslamate-mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf    
    networks:
      tm-net:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"        
    volumes:
      - /root/docker/teslamate/mosquitto-conf:/mosquitto/config
      - /root/docker/teslamate/mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

networks:
  tm-net:
  caddy-net:
    external: true
    name: caddy-net  
```

### Type of installation

Docker

### Teslamate Version

v1.29.1
