### ISSUE TITLE
Bug with docker and grafana:latest

### ISSUE THREAD

**Issue by murmeltier08** [teslamate-org/teslamate#4106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If i use teslamate/grafana:latest I get a error message from grafana.
![image](https://github.com/user-attachments/assets/6b2313b8-8f2f-4a5f-9fe0-e0f0d92facc6)

```
version: '3.5'

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=
      - DATABASE_USER=teslamate
      - DATABASE_PASS=
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - /docker/tesla/teslamate:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=teslamate
    volumes:
      - /docker/tesla/postgres:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    user: "0"
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - /docker/tesla/grafana:/var/lib/grafana
     # - /docker/tesla/grafanaini/grafana.ini:/etc/grafana/grafana.ini

  #mosquitto:
  #  image: eclipse-mosquitto:2
  #  restart: always
  #  command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
  #  volumes:
  #    - mosquitto-conf:/mosquitto/config
  #    - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
 # mosquitto-conf:
 # mosquitto-data:
```

I was not able to use it, i switch e.g. to teslamate/grafana:1.28.0 and it works.

### Expected Behavior

Also the current version works.

### Relevant log output

```shell
not important.
```

### Type of installation

Docker

### Version

current
