### ISSUE TITLE
Enabling pg_stat_statements in Docker Compose

### ISSUE THREAD

**Issue by swiffer** [teslamate-org/teslamate#4269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are multiple slow downs over time which have been adressed in different issues / PRs by adding Indexes or rewriting Queries.

### Expected Behavior

To be able to monitor Query Performance proactively it would be great to have [pg_stat_statements](https://www.postgresql.org/docs/current/pgstatstatements.html#PGSTATSTATEMENTS-COLUMNS) enabled at least in instances of contributors, maybe in all instances.

This allows getting Query Count & Average Execution Times for Queries to take action where needed and ensure optimal Instance Performance.

These Stats could also be be used in Custom Teslamate Dashboards ([Database Info](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/main/dashboards/DatabaseDashboadInfo.json)).

The change would be a rather simple addition to the docker compose file (adding the command) and a database migration (to enable the views required to retrieve the stats) or even better, we could incorporate that dashboard and add pg_stat_statement derived statistics.

While it might sounds like beeing overwhelming for the average users as most users are operating their instance themselves i think it's great to make it easier / more transparent on how their instances are performing and what issues they are facing.

```yaml
database:
    image: postgres:17
    restart: always
    command: postgres -c default_toast_compression=lz4 -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=****
      - POSTGRES_DB=teslamate
      - TZ=Europe/Berlin
    volumes:
      - teslamate-db:/var/lib/postgresql/data
```

```sql
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
```

### Relevant log output

```shell
-
```

### Type of installation

Docker

### Version

v1.30.1
