### ISSUE TITLE
Unable to access teslamate on port 4000, if db is not running

### ISSUE THREAD

**Issue by naaronne** [teslamate-org/teslamate#4555]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?
This is a fresh install on a fresh install of Ubuntu 24.04

I'm unable to connect to the teslamate app on port 4000.  I receive a `Unable to connect` message.

When I attempt to do triaging, I'm unable to connect to the container with the following error:

`Error response from daemon: Container fa619cdeeee992d89d5ace9f9d1c908864eebd005ad1a37b60280aef66e941c7 is restarting, wait until the container is running`

When I do a `docker compose ps` I see the container is in a `restarting` state.

`fa619cdeeee9   teslamate/teslamate:latest   "tini -- /bin/sh /en…"   3 days ago       Restarting (1) 59 seconds ago`

### Expected Behavior

I can connect to the teslamate on port 4000.

### Steps To Reproduce

do a fresh install of teslamate

### Relevant log output

```shell
teslamate-1  | The full error report is shown below.
teslamate-1  | 
teslamate-1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2969ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate-1  | 
teslamate-1  |   1. Ensuring your database is available and that you can connect to it
teslamate-1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate-1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate-1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate-1  | 
teslamate-1  | See DBConnection.start_link/2 for more information
teslamate-1  | 
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1203: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:779: Ecto.Migrator.verbose_schema_migration/3
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:563: Ecto.Migrator.lock_for_migrations/4
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:432: Ecto.Migrator.run/4
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
teslamate-1  |     nofile:1: (file)
teslamate-1  | 2025-02-24 16:19:48.932 [error] Postgrex.Protocol (#PID<0.173.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate-1  | 2025-02-24 16:19:48.932 [error] Postgrex.Protocol (#PID<0.172.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate-1  | 2025-02-24 16:19:50.320 [error] Postgrex.Protocol (#PID<0.172.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate-1  | 2025-02-24 16:19:51.358 [error] Postgrex.Protocol (#PID<0.173.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate-1  | 2025-02-24 16:19:51.879 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate-1  | 
teslamate-1  |   * The database does not exist
teslamate-1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate-1  |     migrations, was defined by another library
teslamate-1  |   * There is a deadlock while migrating (such as using concurrent
teslamate-1  |     indexes with a migration_lock)
teslamate-1  | 
teslamate-1  | To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
teslamate-1  | 
teslamate-1  | To address the second, you can run "mix ecto.drop" followed by
teslamate-1  | "mix ecto.create", both for the desired MIX_ENV. Alternatively you may
teslamate-1  | configure Ecto to use another table and/or repository for managing
teslamate-1  | migrations:
teslamate-1  | 
teslamate-1  |     config :teslamate, TeslaMate.Repo,
teslamate-1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate-1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate-1  | 
teslamate-1  | The full error report is shown below.
teslamate-1  | 
teslamate-1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2973ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate-1  | 
teslamate-1  |   1. Ensuring your database is available and that you can connect to it
teslamate-1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate-1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate-1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate-1  | 
teslamate-1  | See DBConnection.start_link/2 for more information
teslamate-1  | 
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1203: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:779: Ecto.Migrator.verbose_schema_migration/3
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:563: Ecto.Migrator.lock_for_migrations/4
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:432: Ecto.Migrator.run/4
teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
teslamate-1  |     nofile:1: (file)
```

### Type of installation

Docker

### Version

latest

**Comment by JakobLichterfeld** [comment]
Thanks for reporting.

Can you please share your docker-compose.yml (without your secrets)?

From the logs it is clear, that your PostgreSQL database is either not running at all or not accessible.

**Comment by naaronne** [comment]
Hi @JakobLichterfeld , i copied and used the example provided in the docs.  I actually didn't change the docker compose file as I was just attempting to play around initially.

```
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=secretkey #replace with a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS=password #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=password #insert your secure database password!
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=password #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```
