### ISSUE TITLE
teslamate in crash loop after 2.0 migration

### ISSUE THREAD

**Issue by neocorp** [teslamate-org/teslamate#4736]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Hi, I've upgraded teslamate to 2.0.0 recently, following the migration steps on the release page. Everything worked out fine until I started teslamate again after db restore.
It's in a constant crash loop and it seems somehow cannot communicate with postgres. 

I can access Grafana and it seems to be able to connect to postgres just fine, I can see all my data restored. Also no logs observed in postgres container. Although I must say that Grafana fetches data slower than the previous version.

I appreciate the guidance/help in advance!

Below are the logs for your reference.

Here's my `docker-compose.yaml` for reference:

```
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - CHECK_ORIGIN=true
      - TZ=${TM_TZ}
    volumes:
      - ./import:/opt/app/import
    labels:
      - "traefik.enable=true"
      - "traefik.port=4000"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/.htpasswd"
      - "traefik.http.routers.teslamate-insecure.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate-insecure.middlewares=redirect"
      - "traefik.http.routers.teslamate-ws.rule=Host(`${FQDN_TM}`) && Path(`/live/websocket`)"
      - "traefik.http.routers.teslamate-ws.entrypoints=websecure"
      - "traefik.http.routers.teslamate-ws.tls"
      - "traefik.http.routers.teslamate.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate.middlewares=auth"
      - "traefik.http.routers.teslamate.entrypoints=websecure"
      - "traefik.http.routers.teslamate.tls.certresolver=tmhttpchallenge"
    cap_drop:
      - all

  database:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana-insecure.rule=Host(`${FQDN_GRAFANA}`)"
      - "traefik.http.routers.grafana-insecure.middlewares=redirect"
      - "traefik.http.routers.grafana.rule=Host(`${FQDN_GRAFANA}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=tmhttpchallenge"

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 127.0.0.1:1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  proxy:
    image: traefik:v2.2
    restart: always
    command:
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.tmhttpchallenge.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.tmhttpchallenge.acme.storage=/etc/acme/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.htpasswd:/auth/.htpasswd
      - ./acme/:/etc/acme/
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

### Expected Behavior

teslamate should run without errors and be accessible

### Steps To Reproduce

Having a teslamate version e.g. v1.32.0, follow the step to upgrade teslamate to v2.0.0

### Relevant log output

```shell
2025-05-10 15:11:34.895 [info] Migrations already up
2025-05-10 15:12:09.624 [info] No tzdata release files found in custom data dir. Copying release file from tzdata priv dir.
2025-05-10 15:12:10.395 [info] System Info: Erlang/OTP 26 (jit)
2025-05-10 15:12:10.395 [info] Version: 2.0.0
PostgreSQL version 17.5 is compatible (17.x series).
2025-05-10 15:12:12.989 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (1095.727 ms)
2025-05-10 15:12:12.990 [info] Refreshed api tokens
2025-05-10 15:12:12.998 [info] Scheduling token refresh in 6 h
2025-05-10 15:12:13.006 [info] Running TeslaMateWeb.Endpoint with cowboy 2.13.0 at :::4000 (http)
2025-05-10 15:12:13.011 [info] Access TeslaMateWeb.Endpoint at XXX.com
2025-05-10 15:12:13.648 [info] Starting logger for 'Some Tesla'
2025-05-10 15:12:14.134 [info] tzdata release in place is from a file last modified Thu, 05 Sep 2024 18:47:42 GMT. Release file on server was last modified Sat, 22 Mar 2025 21:45:31 GMT.
2025-05-10 15:12:14.389 [info] MQTT connection has been established
2025-05-10 15:12:37.152 [info] Tzdata has updated the release from 2024b to 2025b
2025-05-10 15:13:13.152 [error] Postgrex.Protocol (#PID<0.2461.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2703.0> timed out because it queued and checked out the connection for longer than 60000ms

#PID<0.2703.0> was at location:

    :prim_inet.recv0/3
    (postgrex 0.20.0) lib/postgrex/protocol.ex:3259: Postgrex.Protocol.msg_recv/4
    (postgrex 0.20.0) lib/postgrex/protocol.ex:2261: Postgrex.Protocol.recv_bind/3
    (postgrex 0.20.0) lib/postgrex/protocol.ex:2153: Postgrex.Protocol.bind_execute/4
    (db_connection 2.7.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.7.0) lib/db_connection.ex:1558: DBConnection.run_execute/5
    (db_connection 2.7.0) lib/db_connection.ex:1653: DBConnection.run/6
    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5

2025-05-10 15:13:13.910 [error] GenStateMachine TeslaMate.Terrain terminating
** (DBConnection.ConnectionError) tcp recv (idle): closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (teslamate 2.0.0) lib/teslamate/log.ex:189: TeslaMate.Log.get_positions_without_elevation/2
    (teslamate 2.0.0) lib/teslamate/terrain.ex:77: TeslaMate.Terrain.handle_event/4
    (stdlib 5.2.3.3) gen_statem.erl:1397: :gen_statem.loop_state_callback/11
    (stdlib 5.2.3.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
2025-05-10 15:13:14.135 [error] Postgrex.Protocol (#PID<0.2464.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2719.0> timed out because it queued and checked out the connection for longer than 60000ms

#PID<0.2719.0> was at location:

    :prim_inet.recv0/3
    (postgrex 0.20.0) lib/postgrex/protocol.ex:3259: Postgrex.Protocol.msg_recv/4
    (postgrex 0.20.0) lib/postgrex/protocol.ex:2261: Postgrex.Protocol.recv_bind/3
    (postgrex 0.20.0) lib/postgrex/protocol.ex:2153: Postgrex.Protocol.bind_execute/4
    (db_connection 2.7.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.7.0) lib/db_connection.ex:1558: DBConnection.run_execute/5
    (db_connection 2.7.0) lib/db_connection.ex:1653: DBConnection.run/6
    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5

2025-05-10 15:13:14.656 [error] GenStateMachine :"1" terminating
** (DBConnection.ConnectionError) tcp recv (idle): closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
    (teslamate 2.0.0) lib/teslamate/vehicles/vehicle.ex:1207: TeslaMate.Vehicles.Vehicle.restore_last_known_values/2
    (teslamate 2.0.0) lib/teslamate/vehicles/vehicle.ex:343: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib 5.2.3.3) gen_statem.erl:1397: :gen_statem.loop_state_callback/11
2025-05-10 15:13:27.384 [info] GET /
2025-05-10 15:13:33.152 [error] #PID<0.2747.0> running TeslaMateWeb.Endpoint (connection #PID<0.2746.0>, stream id 1) terminated
Server: teslamate.niyazierdogan.ch:80 (http)
Request: GET /
** (exit) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
2025-05-10 15:14:14.390 [error] Postgrex.Protocol (#PID<0.2467.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2743.0> timed out because it queued and checked out the connection for longer than 60000ms

#PID<0.2743.0> was at location:

    :prim_inet.recv0/3
    (postgrex 0.20.0) lib/postgrex/protocol.ex:3259: Postgrex.Protocol.msg_recv/4
    (postgrex 0.20.0) lib/postgrex/protocol.ex:2261: Postgrex.Protocol.recv_bind/3
    (postgrex 0.20.0) lib/postgrex/protocol.ex:2153: Postgrex.Protocol.bind_execute/4
    (db_connection 2.7.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.7.0) lib/db_connection.ex:1558: DBConnection.run_execute/5
    (db_connection 2.7.0) lib/db_connection.ex:1653: DBConnection.run/6
    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5

2025-05-10 15:14:14.636 [error] GenStateMachine TeslaMate.Terrain terminating
** (DBConnection.ConnectionError) tcp recv (idle): closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (teslamate 2.0.0) lib/teslamate/log.ex:189: TeslaMate.Log.get_positions_without_elevation/2
    (teslamate 2.0.0) lib/teslamate/terrain.ex:77: TeslaMate.Terrain.handle_event/4
    (stdlib 5.2.3.3) gen_statem.erl:1397: :gen_statem.loop_state_callback/11
    (stdlib 5.2.3.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
2025-05-10 15:14:15.634 [error] Postgrex.Protocol (#PID<0.2459.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2744.0> timed out because it queued and checked out the connection for longer than 60000ms

#PID<0.2744.0> was at location:

    :prim_inet.recv0/3
    (postgrex 0.20.0) lib/postgrex/protocol.ex:3259: Postgrex.Protocol.msg_recv/4
    (postgrex 0.20.0) lib/postgrex/protocol.ex:2261: Postgrex.Protocol.recv_bind/3
    (postgrex 0.20.0) lib/postgrex/protocol.ex:2153: Postgrex.Protocol.bind_execute/4
    (db_connection 2.7.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.7.0) lib/db_connection.ex:1558: DBConnection.run_execute/5
    (db_connection 2.7.0) lib/db_connection.ex:1653: DBConnection.run/6
    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5
```

### Type of installation

Docker

### Version

v2.0.0

### Are you running latest major supported PostgreSQL version?

- [x] I run the latest major supported PostgreSQL version
